/* $Id: StraightLadder102.mac,v1.0.0 2019/08/27 Jack.Leng $ */

/*
**	这个程序用于参数化生成直梯.
*/

#include "include/dmutil.h"
#include "include/win.h"
#include "include/win_panel.h"
#include "include/PmMgeTags.h"
#include "include/pm.h"
#include "include/pm_core_tags.h"
#include "include/array.mac"
#include "include/geoutils.h"
#include "include/cos.h"
#include "include/quants.h"
#include "include/dm_cos_schema.h"

#include "$MarineToolkit/Structural/StraightLadder.h"
#include "$MarineToolkit/Include/Common_Utility.h"
#include "$MarineToolkit/Include/Structural_Utility.h"
#include "$MarineToolkit/Include/Math_Utility.h"

global handle   Ladder_Handle;
global handle   MainWindow;
global string    Icon_Path   = "$MarineToolkit/ICONS/StraightLadder/";

/* 面板 */
global handle Template, Information, Material, Command, Parameters, Position, Orientation;

/* 控件 */
global handle System_Name, Select_System, Ladder_Name, Pick_Ladder, Ladder_Description, Planning_Unit;
global handle Ladder_Part1, Ladder_Part2, Ladder_Part3, Ladder_Part4, Ladder_Part5, Ladder_Part6;
global handle Select_Ladder_Part1, Select_Ladder_Part2, Select_Ladder_Part3;
global handle Select_Ladder_Part4, Select_Ladder_Part5, Select_Ladder_Part6;
global handle Ladder_Para_L, Ladder_Para_W, Ladder_Para_h, Ladder_Para_h1, Ladder_Para_h2;
global handle Ladder_Para_d1, Ladder_Para_d2;
global handle Ladder_Para_a, Ladder_Para_b, Ladder_Para_r;
global handle Ladder_Para_ad, Ladder_Para_bd;

global handle Ladder_Bolt_Switch, Ladder_Nut_Switch, Ladder_Washer_Switch, Ladder_Pad_Switch;

global handle Ladder_Position_X,Ladder_Position_Xref,Ladder_Position_Xoff;
global handle Ladder_Position_Y,Ladder_Position_Yref,Ladder_Position_Yoff;
global handle Ladder_Position_Z,Ladder_Position_Zref,Ladder_Position_Zoff;
global handle Rotate_By_X_L,Rotate_By_X_R,Rotate_By_Y_L,Rotate_By_Y_R,Rotate_By_Z_L,Rotate_By_Z_R;
global handle Ladder_Rotate_Angle_X,Ladder_Rotate_Angle_Y,Ladder_Rotate_Angle_Z;
global handle Move_By_X_P,Move_By_X_N,Move_By_Y_P,Move_By_Y_N,Move_By_Z_P,Move_By_Z_N;
global handle Ladder_Move_Distance_X,Ladder_Move_Distance_Y,Ladder_Move_Distance_Z;
global handle Create_Ladder;

/* 直梯信息 */
global string Info_System_Name = "";
global int    Info_System_Id = 0;
global string Info_Ladder_Name = "";
global string Info_Ladder_Desc = "Undefined";
global string Info_Planning_Unit = "999";
global string Info_Ladder_Type = "StraightLadder102";

/* part id of ladder material */
global string Ladder_Part1_Pid = "";
global string Ladder_Part2_Pid = "";
global string Ladder_Part3_Pid = ""; 
global string Ladder_Part4_Pid = ""; 
global string Ladder_Part5_Pid = "";
global string Ladder_Part6_Pid = "";

/* ladder size */
global float Ladder_Size_L  = 0;
global float Ladder_Size_W  = 0;
global float Ladder_Size_h  = 0;
global float Ladder_Size_h1 = 0;
global float Ladder_Size_h2 = 0;
global float Ladder_Size_d1 = 0;
global float Ladder_Size_d2 = 0;
global float Ladder_Size_a  = 0;
global float Ladder_Size_b  = 0;
global float Ladder_Size_r  = 0;
global float Ladder_Size_ad = 0;
global float Ladder_Size_bd = 0;

/* ladder fixd size */
global float Ladder_Size_Step_Extend = 5;

/* part data */
global handle Part11,Part12;
global handle Part13,Part14,Part15,Part16;
global handle Part21,Part22;
global handle Part31,Part32,Part33,Part34;
global handle Part41,Part42,Part43,Part44;
global handle Part51,Part52,Part53,Part54;
global handle Part61,Part62,Part63,Part64;

/*ladder position*/
global float Ladder_X0 = 0; 
global float Ladder_Y0 = 0;
global float Ladder_Z0 = 0;

/*ladder direction*/
global float Ladder_X_Dx = 1;
global float Ladder_X_Dy = 0;
global float Ladder_X_Dz = 0;
global float Ladder_Y_Dx = 0;
global float Ladder_Y_Dy = 1;
global float Ladder_Y_Dz = 0;

/*ladder modify flag*/
global int Modify_flag = 0;

/*with pad flag*/
global string Bolt_Switch   = "on";
global string Nut_Switch    = "on";
global string Washer_Switch = "on";
global string Pad_Switch    = "on";

/*
**创建顶层窗体
*/
create_top_frame()
{
	mainform = W_INIT_FRAME();
	W_REALIZE_WINDOW(mainform, W_FRAME_TITLE, "直梯");	
	return(mainform);	
}

/*
**创建用于显示直梯模板的面板
*/
create_template_panel(mainform)
{  
    /* 获取图标保存路径 */
    icon_path = Icon_Path;
    /* 图标完整文件名（包含路径） */
    pic = icon_path + "StraightLadder102.bmp";
   
    /* 向主窗体添加一个面板，用于显示参数化模型样板 */
	Template = W_ADD_WINDOW(mainform, W_PANEL, "Template");
	W_REALIZE_WINDOW(Template, 	W_FRAME_X, 		0,
							    W_FRAME_Y, 		0,
							    W_FRAME_WIDTH,  450,
							    W_FRAME_HEIGHT,	550);	
								
	LblImage_h = W_ADD_PANELITEM(Template, W_PANEL_MESSAGE, "LblImage_h");	
	W_REALIZE_PANELITEM(LblImage_h, 	W_PANEL_X, 			0,
										W_PANEL_Y, 			0,
										W_PANEL_WIDTH,		450,
										W_PANEL_HEIGHT,		550);	
	W_SET_PANELITEM_ARGS(LblImage_h,	W_PANEL_LABELIMAGE,	pic,
										W_PANEL_SHOW, 		1);
	return(Template);
}

/*
**创建用于处理直梯基本信息的面板
*/
create_info_panel(mainform)
{
    /* 创建用于显示直梯主要信息的面板 */
    Information = W_ADD_WINDOW(mainform, W_PANEL, "Information");
   
    /* 设置面板参数 */
	W_REALIZE_WINDOW(Information,	W_FRAME_X, 		465,
							        W_FRAME_Y, 		0,
							        W_FRAME_WIDTH, 	400,
							        W_FRAME_HEIGHT,	100);
							            
	title = W_ADD_PANELITEM(Information, W_PANEL_MESSAGE, "title");
	W_REALIZE_PANELITEM(title,	W_PANEL_ROW,	0,
		                        W_PANEL_COL,	0,
		                        W_PANEL_LABEL,	"直梯信息");

    seperate_line = W_ADD_PANELITEM(Information, W_PANEL_MESSAGE, "seperate_line");
	W_REALIZE_PANELITEM(seperate_line,  W_PANEL_ROW, 		0,
	                                    W_PANEL_COL, 		7,
		                                W_PANEL_LABEL,		"",
		                                W_PANEL_SEPARATOR,	1);
    /* 直梯所属系统 */
	System_Name = W_ADD_PANELITEM(Information, W_PANEL_FILL, "System_Name");
	W_REALIZE_PANELITEM(System_Name,	W_PANEL_ROW, 		1, 
										W_PANEL_COL, 		0,
							            W_PANEL_LABEL, 		"所属系统:   ",
							            W_PANEL_LENGTH, 	25,
							            W_PANEL_VALUE, 		"Undefined",
							            W_PANEL_CALLBACK,	1);
	W_SET_PANELITEM_HANDLER(System_Name, "system_name_handler");   
	
	Select_System = W_ADD_PANELITEM(Information, W_PANEL_BUTTON, "Select_System");
	W_REALIZE_PANELITEM(Select_System,	W_PANEL_ROW, 			1, 
	                                    W_PANEL_COL, 			34,
                  						W_PANEL_BUTTONIMAGE, 	"选择系统", 
                  						W_PANEL_WIDTH, 			10,
                  						W_PANEL_BUTTONVALUE,	100,
                  						W_PANEL_CALLBACK, 		1,
                  						W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Select_System, "select_system_handler"); 			

    /* 直梯编号 */
	Ladder_Name = W_ADD_PANELITEM(Information, W_PANEL_FILL, "Ladder_Name");
	W_REALIZE_PANELITEM(Ladder_Name,	W_PANEL_ROW, 		2, 
                                        W_PANEL_COL, 		0,
                                        W_PANEL_LABEL, 		"直梯编号:   ",
                                        W_PANEL_LENGTH, 	25,
                                        W_PANEL_VALUE, 		"Undefined",
                                        W_PANEL_CALLBACK, 	1);
	W_SET_PANELITEM_HANDLER(Ladder_Name, "ladder_name_handler"); 
	
	Pick_Ladder = W_ADD_PANELITEM(Information, W_PANEL_BUTTON, "Pick_Ladder");
	W_REALIZE_PANELITEM(Pick_Ladder,	W_PANEL_ROW, 			2, 
                                        W_PANEL_COL, 			34,
                                        W_PANEL_BUTTONIMAGE, 	"选择直梯", 
                                        W_PANEL_WIDTH, 			10,
                                        W_PANEL_BUTTONVALUE,	101,
                                        W_PANEL_CALLBACK, 		1,
                                        W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Pick_Ladder, "pick_ladder_handler"); 	
	
    /* 直梯名称 */
	Ladder_Description = W_ADD_PANELITEM(Information, W_PANEL_FILL, "Ladder_Description");
	W_REALIZE_PANELITEM(Ladder_Description, 	W_PANEL_ROW, 		3, 
                                                W_PANEL_COL, 		0,
                                                W_PANEL_LABEL, 		"直梯名称:   ",
                                                W_PANEL_LENGTH, 	25,
                                                W_PANEL_VALUE, 		"Undefined",
                                                W_PANEL_CALLBACK, 	1);
	W_SET_PANELITEM_HANDLER(Ladder_Description, "ladder_description_handler"); 

	/* 直梯托盘 */
	Planning_Unit = W_ADD_PANELITEM(Information, W_PANEL_FILL, "Planning_Unit");
	W_REALIZE_PANELITEM(Planning_Unit,	W_PANEL_ROW, 		4, 
										W_PANEL_COL, 		0,
							            W_PANEL_LABEL, 		"托盘名称:   ",
							            W_PANEL_LENGTH, 	25,
							            W_PANEL_VALUE, 		"Undefined",
							            W_PANEL_CALLBACK, 	1);
	W_SET_PANELITEM_HANDLER(Planning_Unit, "ladder_planning_unit_handler");
	  
    return(Information);
}

system_name_handler(item, event_type, dummy)
{
  return(0); 
}

ladder_name_handler(item, event_type, dummy)
{
	if (event_type == W_EVENT_ITEM_LEFT){
		ladder_name = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
		ladder_handle = PM_FIND_BY_NAME(ladder_name);
      
		/* 如果指定的模型已经存在，则做如下处理 */
		if (ladder_handle != 0){
			group_type = PM_GET_OBJDATA(ladder_handle, 0, MMT_TAG_GROUPTYPE);
			/* 指定的模型不是直梯模型 */
			if (group_type != Group_Type){
				U_CONFIRM("模型已经存在，但不是直梯模型");
				W_SET_PANELITEM_ARGS(Ladder_Name, W_PANEL_VALUE, "Undefined");	
				return(0);
			} 
			/* 指定的模型是直梯模型 */
			else{
				type = PM_GET_OBJDATA(ladder_handle, 0, LadderType);
				if(type != Info_Ladder_Type){
					info = "直梯已经存在且类型为" + type + ",这个程序只能处理类型为" + Info_Ladder_Type + "的直梯。";
					U_CONFIRM(info);
					return(0);
				}   	             
				res = U_YESNO("模型已经存在，是否修改？",1);
				if (res == 1){
					reload_ladder_data(ladder_name);
					W_SET_PANELITEM_ARGS(Create_Ladder, W_PANEL_SENSITIVITY,0);
					Modify_flag = 1;
					return(0);
				}
				else{
					W_SET_PANELITEM_ARGS(item, W_PANEL_VALUE, "Undefined");
					return(0);
				}
			}        
		}
		else{
			W_SET_PANELITEM_ARGS(Create_Ladder, W_PANEL_SENSITIVITY,1); 
			Modify_flag = 0;             
		}
	}
	return(0); 
}

/*矩形板*/
create_rect_curve_with_radius(float length, float width, float radius)
{
    curve = "";
    if(radius == 0){
        p1x = length/2;
        p1y = width/2;
        p2x = p1x;
        p2y = - p1y;
        p3x = - p1x;
        p3y = - p1y;
        p4x = - p1x;
        p4y = p1y;
        
        p1xs = STRINGTERM(FTOASCII(p1x),".")+",";
        p1ys = STRINGTERM(FTOASCII(p1y),".")+",";
        p2xs = STRINGTERM(FTOASCII(p2x),".")+",";
        p2ys = STRINGTERM(FTOASCII(p2y),".")+",";
        p3xs = STRINGTERM(FTOASCII(p3x),".")+",";
        p3ys = STRINGTERM(FTOASCII(p3y),".")+",";
        p4xs = STRINGTERM(FTOASCII(p4x),".")+",";
        p4ys = STRINGTERM(FTOASCII(p4y),".");
        curve = curve+p1xs+p1ys+p2xs+p2ys+p3xs+p3ys+p4xs+p4ys;
    }
    else{
        p1x = -length/2;
        p1y = width/2-radius;
        p2x = p1x;
        p2y = - p1y;
        p3x = p1x - radius*SIN(45) + radius;
        p3y = p2y - radius*COS(45);
        p4x = -length/2 + radius;
        p4y = -width/2;
        p5x = -p4x;
        p5y = p4y;
        p6x = - p3x;
        p6y = p3y;
        p7x = - p2x;
        p7y = p2y;
        p8x = p7x;
        p8y = - p7y;
        p9x = p6x;
        p9y = -p6y;
        p10x = p5x;
        p10y = -p5y;
        p11x = p4x;
        p11y = -p4y;
        p12x = p3x;
        p12y = -p3y;

        p1xs = STRINGTERM(FTOASCII(p1x),".")+",";
        p1ys = STRINGTERM(FTOASCII(p1y),".")+",";
        p2xs = STRINGTERM(FTOASCII(p2x),".")+",";
        p2ys = STRINGTERM(FTOASCII(p2y),".")+",";
        p3xs = STRINGTERM(FTOASCII(p3x),".")+",";
        p3ys = STRINGTERM(FTOASCII(p3y),".")+",";
        p4xs = STRINGTERM(FTOASCII(p4x),".")+",";
        p4ys = STRINGTERM(FTOASCII(p4y),".")+",";
        p5xs = STRINGTERM(FTOASCII(p5x),".")+",";
        p5ys = STRINGTERM(FTOASCII(p5y),".")+",";
        p6xs = STRINGTERM(FTOASCII(p6x),".")+",";
        p6ys = STRINGTERM(FTOASCII(p6y),".")+",";
        p7xs = STRINGTERM(FTOASCII(p7x),".")+",";
        p7ys = STRINGTERM(FTOASCII(p7y),".")+",";
        p8xs = STRINGTERM(FTOASCII(p8x),".")+",";
        p8ys = STRINGTERM(FTOASCII(p8y),".")+",";
        p9xs = STRINGTERM(FTOASCII(p9x),".")+",";
        p9ys = STRINGTERM(FTOASCII(p9y),".")+",";
        p10xs = STRINGTERM(FTOASCII(p10x),".")+",";
        p10ys = STRINGTERM(FTOASCII(p10y),".")+",";
        p11xs = STRINGTERM(FTOASCII(p11x),".")+",";
        p11ys = STRINGTERM(FTOASCII(p11y),".")+",";
        p12xs = STRINGTERM(FTOASCII(p12x),".")+",";
        p12ys = STRINGTERM(FTOASCII(p12y),".")+",";
        p1ys0 = STRINGTERM(FTOASCII(p1y),".");
        curve = curve+p1xs+p1ys+p2xs+p2ys+"ARP,"+p3xs+p3ys+p4xs+p4ys+p5xs+p5ys+"ARP,"+p6xs+p6ys+p7xs+p7ys+p8xs+p8ys+"ARP,"+p9xs+p9ys+p10xs+p10ys+p11xs+p11ys+"ARP,"+p12xs+p12ys+p1xs+p1ys0;
    }
	return(curve);
}

/*矩形板*/
create_rect_curve(float length, float width)
{	
	p1x = length/2;
	p1y = width/2;				
	p2x = p1x;
	p2y = -p1y;			
	p3x = -p1x;
	p3y = -p1y;				
	p4x = -p1x;
	p4y = p1y;		
	 	
	p1xs = STRINGTERM(FTOASCII(p1x),".")+",";
	p1ys = STRINGTERM(FTOASCII(p1y),".")+",";
	p2xs = STRINGTERM(FTOASCII(p2x),".")+",";
	p2ys = STRINGTERM(FTOASCII(p2y),".")+",";
	p3xs = STRINGTERM(FTOASCII(p3x),".")+",";
	p3ys = STRINGTERM(FTOASCII(p3y),".")+",";	
	p4xs = STRINGTERM(FTOASCII(p4x),".")+",";
	p4ys = STRINGTERM(FTOASCII(p4y),".");	
		
	curve = "";
	curve = curve+p1xs+p1ys+p2xs+p2ys+p3xs+p3ys+p4xs+p4ys;     
	return(curve);   
}

/*凹槽板*/
create_aocao_curve(float size11,float size12,float size21,float size22,float offset)
{	
	p1x = size11/2;
	p1y = size12/2;				
	p2x = p1x;
	p2y = -p1y;			
	p3x = -p1x;
	p3y = -p1y;				
	p4x = -p1x;
	p4y = p1y;		
	p5x = offset-0.5*size21;
	p5y = p1y;	
	p6x = offset-0.5*size21;
	p6y = p1y-size22;	
	p7x = offset+0.5*size21;
	p7y = p1y-size22;	
	p8x = offset+0.5*size21;
	p8y = p1y;
    
	p1xs = STRINGTERM(FTOASCII(p1x),".")+",";
	p1ys = STRINGTERM(FTOASCII(p1y),".")+",";
	p2xs = STRINGTERM(FTOASCII(p2x),".")+",";
	p2ys = STRINGTERM(FTOASCII(p2y),".")+",";
	p3xs = STRINGTERM(FTOASCII(p3x),".")+",";
	p3ys = STRINGTERM(FTOASCII(p3y),".")+",";	
	p4xs = STRINGTERM(FTOASCII(p4x),".")+",";
	p4ys = STRINGTERM(FTOASCII(p4y),".")+",";	
	p5xs = STRINGTERM(FTOASCII(p5x),".")+",";
	p5ys = STRINGTERM(FTOASCII(p5y),".")+",";
	p6xs = STRINGTERM(FTOASCII(p6x),".")+",";
	p6ys = STRINGTERM(FTOASCII(p6y),".")+",";	
	p7xs = STRINGTERM(FTOASCII(p7x),".")+",";
	p7ys = STRINGTERM(FTOASCII(p7y),".")+",";	
	p8xs = STRINGTERM(FTOASCII(p8x),".")+",";
	p8ys = STRINGTERM(FTOASCII(p8y),".");	
    
	curve = "";
	curve = curve+p1xs+p1ys+p2xs+p2ys+p3xs+p3ys+p4xs+p4ys+p5xs+p5ys+p6xs+p6ys+p7xs+p7ys+p8xs+p8ys;     
	return(curve);   
}

create_subplate_curve(float L1, float W1, float c, float d)
{	
	p1x = d;
	p1y = c;				
	p2x = - L1 + d;
	p2y = c;			
	p3x = - L1 + d;
	p3y = - W1 + c;				
	p4x = d;
	p4y = - W1 + c;		
	 	
	p1xs = STRINGTERM(FTOASCII(p1x),".")+",";
	p1ys = STRINGTERM(FTOASCII(p1y),".")+",";
	p2xs = STRINGTERM(FTOASCII(p2x),".")+",";
	p2ys = STRINGTERM(FTOASCII(p2y),".")+",";
	p3xs = STRINGTERM(FTOASCII(p3x),".")+",";
	p3ys = STRINGTERM(FTOASCII(p3y),".")+",";	
	p4xs = STRINGTERM(FTOASCII(p4x),".")+",";
	p4ys = STRINGTERM(FTOASCII(p4y),".");	
		
	curve = "";
	curve = curve+p1xs+p1ys+p2xs+p2ys+p3xs+p3ys+p4xs+p4ys;     
	return(curve);   
}

ladder_description_handler(item, event_type, dummy)
{   
	if (event_type == W_EVENT_ITEM_LEFT){
		Info_Ladder_Desc = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
		SET_STRING_DEFAULT("StraightLadder102", "Info_Ladder_Desc", Info_Ladder_Desc);
		if(Modify_flag){
			set_ladder_para(Ladder_Handle);
		}
	}
	return(0); 
}

ladder_planning_unit_handler(item, event_type, dummy)
{   
	if (event_type == W_EVENT_ITEM_LEFT){
		Info_Planning_Unit = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
		SET_STRING_DEFAULT("StraightLadder102", "Planning_Unit", Info_Planning_Unit);
	}
	return(0); 
}

select_system_handler(item, event_type, button_value)
{
	system_name = PM_SELECT_SYSTEM();
	if(ISINT(system_name)){
		U_MESSAGE("系统选择取消");
		return(0);
	}
	else {
		U_MESSAGE("选择系统<" + system_name + ">");
		Info_System_Name = system_name;
		Info_System_Id = PM_GET_SYSTEM_ID(system_name);
		W_SET_PANELITEM_ARGS(System_Name, W_PANEL_VALUE, system_name);
		SET_STRING_DEFAULT("StraightLadder102", "System_Name", system_name);
	}			
	return(0);   
}

pick_ladder_handler(item, event_type, button_value)
{
	tmp = 0;
	picked_object_handle = PM_PICK_OBJECT("请选择直梯", tmp, "STRUCTCMP","BEAM");
	if (!ISINT(picked_object_handle)){	   
		/*获取直梯的名称*/
		group_handle = PM_GET_OBJECT_GROUP(picked_object_handle, Group_Type_I);
		if (ISINT(group_handle)){
			U_CONFIRM("此零件不属于任何直梯");
			W_SET_PANELITEM_ARGS(Ladder_Name, W_PANEL_VALUE, "Undefined");	
			return(0);
		}
	    
		group_name = PM_GET_OBJDATA(group_handle,0, MMT_TAG_OBJNAME);	
		/* 判断直梯类型是否匹配 */
		type = PM_GET_OBJDATA(group_handle,0, LadderType);
		if(ISINT(type)){
			U_CONFIRM("此零件不属于任何直梯");
			W_SET_PANELITEM_ARGS(Ladder_Name, W_PANEL_VALUE, "Undefined");	
			return(0);	      
		}
		if(type != Info_Ladder_Type){
			info = "选择的直梯类型为" + type + ",这个程序只能处理类型为" + Info_Ladder_Type + "的直梯。";
			U_CONFIRM(info);
			return(0);
		}	   	      		
		/*获取直梯的尺寸参数及其它相关信息*/
        initialize();	
		reload_ladder_data(group_name);	
		W_SET_PANELITEM_ARGS(Create_Ladder, W_PANEL_SENSITIVITY,0);
		Modify_flag = 1;					
	} 
	return(0); 
}

reload_ladder_data(string ladder_name)
{
    W_SET_PANELITEM_ARGS(Ladder_Name, W_PANEL_VALUE, ladder_name);	
    group_handle = PM_FIND_BY_NAME(ladder_name);
    Ladder_Handle = group_handle;
    read_model_size();

    /*获取并设置直梯的零件信息*/
    parts = PM_GET_OBJECTS_IN_GROUP(Ladder_Handle);
    p_number = PM_NR_MEMBERS_IN_SET(parts);
    part1_1 = "";
    part2_1 = "";
    part3_1 = "";
    part4_1 = "";
    part5_1 = "";
    part6_1 = "";
    ladder_bolt_switch("0");
    ladder_nut_switch("0");
    ladder_washer_switch("0");
    ladder_pad_switch("0");
    W_SET_PANELITEM_ARGS(Ladder_Bolt_Switch, W_PANEL_VALUE, "0");
    W_SET_PANELITEM_ARGS(Ladder_Nut_Switch, W_PANEL_VALUE, "0");
    W_SET_PANELITEM_ARGS(Ladder_Washer_Switch, W_PANEL_VALUE, "0");
    W_SET_PANELITEM_ARGS(Ladder_Pad_Switch, W_PANEL_VALUE, "0");
    /*获取并设置直梯零件的零件材料*/
    for (i = 0; i < p_number; i = i + 1;){
        part = PM_GET_MEMBER_IN_SET(parts, i);
        part_number = Get_Attribute_Value(part,PartNumber);
        if (part_number == "1-1"){
            part1_1 = part;
            part_id = PM_GET_OBJDATA(part, 0, MMT_TAG_PARTID);
            Ladder_Part1_Pid = part_id;
            descr = Pid_To_Description(part_id);
            W_SET_PANELITEM_ARGS(Ladder_Part1, W_PANEL_VALUE, descr);
            SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part1_Pid", part_id);   
        }              
        else if (part_number == "2-1"){
            part2_1 = part;
            part_id = PM_GET_OBJDATA(part, 0, MMT_TAG_PARTID);
            Ladder_Part2_Pid = part_id;
            descr = Pid_To_Description(part_id);
            W_SET_PANELITEM_ARGS(Ladder_Part2, W_PANEL_VALUE, descr);
            SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part2_Pid", part_id); 
        }  
        else if (part_number == "3-1"){
            part_id = PM_GET_OBJDATA(part, 0, MMT_TAG_PARTID);
            Ladder_Part3_Pid = part_id;
            descr = Pid_To_Description(part_id);
            W_SET_PANELITEM_ARGS(Ladder_Part3, W_PANEL_VALUE, descr);
            SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part3_Pid", part_id);
            ladder_bolt_switch("1");
            W_SET_PANELITEM_ARGS(Ladder_Bolt_Switch, W_PANEL_VALUE, "1");
        } 
        else if (part_number == "4-1"){
            part_id = PM_GET_OBJDATA(part, 0, MMT_TAG_PARTID);
            Ladder_Part4_Pid = part_id;
            descr = Pid_To_Description(part_id);
            W_SET_PANELITEM_ARGS(Ladder_Part4, W_PANEL_VALUE, descr);
            SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part4_Pid", part_id);
            ladder_nut_switch("1");
            W_SET_PANELITEM_ARGS(Ladder_Nut_Switch, W_PANEL_VALUE, "1");
        }     
        else if (part_number == "5-1"){
            part_id = PM_GET_OBJDATA(part, 0, MMT_TAG_PARTID);
            Ladder_Part5_Pid = part_id;
            descr = Pid_To_Description(part_id);
            W_SET_PANELITEM_ARGS(Ladder_Part5, W_PANEL_VALUE, descr);
            SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part5_Pid", part_id);
            ladder_washer_switch("1");
            W_SET_PANELITEM_ARGS(Ladder_Washer_Switch, W_PANEL_VALUE, "1");
        } 
        else if (part_number == "6-1"){
            part_id = PM_GET_OBJDATA(part, 0, MMT_TAG_PARTID);
            Ladder_Part6_Pid = part_id;
            descr = Pid_To_Description(part_id);
            W_SET_PANELITEM_ARGS(Ladder_Part6, W_PANEL_VALUE, descr);
            SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part6_Pid", part_id);  
            ladder_pad_switch("1");   
            W_SET_PANELITEM_ARGS(Ladder_Pad_Switch, W_PANEL_VALUE, "1");            
        }  
    }

	/*获取直梯所属系统 */
	part0 = PM_GET_MEMBER_IN_SET(parts, 0);
	sys = PM_GET_OBJDATA(part0,0,"sys");
	if (!ISINT(sys)){
        Info_System_Name = sys;
	    Info_System_Id = PM_GET_SYSTEM_ID(Info_System_Name);
		W_SET_PANELITEM_ARGS(System_Name, W_PANEL_VALUE, Info_System_Name);
		SET_STRING_DEFAULT("StraightLadder102", "System_Name", Info_System_Name);	   
    } 
    
	/*获取直梯的描述 */
	des = PM_GET_OBJDATA(part0,0,LadderDes);
	if(!ISINT(des)){
        Info_Ladder_Desc = des;
		W_SET_PANELITEM_ARGS(Ladder_Description, W_PANEL_VALUE, des);
		SET_STRING_DEFAULT("StraightLadder102", "Info_Ladder_Desc", des);
    }
    
	/*获取直梯的托盘 */
	pla = PM_GET_OBJDATA(part0,0,PlanningUnit);
	if(!ISINT(pla)){
        planningunit = pla;
		W_SET_PANELITEM_ARGS(Planning_Unit, W_PANEL_VALUE, pla);
		SET_STRING_DEFAULT("StraightLadder102", "Planning_Unit", pla);
    }

	/*获取直梯的方向 */
    ux=0;uy=0;uz=0;
    vx=0;vy=0;vz=0;
    get_part_orientation(part1_1, ux,uy,uz, vx,vy,vz);
    Ladder_X_Dx = ux;
    Ladder_X_Dy = uy;
    Ladder_X_Dz = uz;
    Ladder_Y_Dx = vx;
    Ladder_Y_Dy = vy;
    Ladder_Y_Dz = vz;

	/*获取直梯的坐标 */
	x1 = 0.0;	 y1 = 0.0;	  z1 = 0.0;	
    x2 = 0.0;	 y2 = 0.0;	  z2 = 0.0;
	x_dx = 0.0;	 x_dy = 0.0;  x_dz = 0.0;
	end1x = 0.0; end1y = 0.0; end1z = 0.0;
	end2x = 0.0; end2y = 0.0; end2z = 0.0;	
	Get_Beam_Para(part2_1,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,end1x,end1y,end1z,end2x,end2y,end2z);
	x0 = (x1 + x2)/2.0;
	y0 = (y1 + y2)/2.0;
	z0 = (z1 + z2)/2.0;
    Point_Move(x0,y0,z0, x0,y0,z0, vx,vy,vz, Ladder_Size_d1);

	Ladder_X0 = x0;
	Ladder_Y0 = y0;
	Ladder_Z0 = z0;
    W_SET_NUMERIC_VALUE(Ladder_Position_X, Ladder_X0);
    W_SET_NUMERIC_VALUE(Ladder_Position_Y, Ladder_Y0);
    W_SET_NUMERIC_VALUE(Ladder_Position_Z, Ladder_Z0);

    /* 将绝对坐标转换成相对坐标并显示到面板中 */
    /* convert abstract coordinate value into reference and display on panel */
    x_ref = "";
    y_ref = "";
    z_ref = "";
    x_offset = 0;
    y_offset = 0;
    z_offset = 0;
   
    res = GetReferenceCoords(Ladder_X0, Ladder_Y0, Ladder_Z0, x_ref, x_offset, y_ref, y_offset, z_ref, z_offset);
    if (res == 0){
        W_SET_PANELITEM_ARGS(Ladder_Position_Xref, W_PANEL_VALUE, x_ref);
        W_SET_PANELITEM_ARGS(Ladder_Position_Yref, W_PANEL_VALUE, y_ref);
        W_SET_PANELITEM_ARGS(Ladder_Position_Zref, W_PANEL_VALUE, z_ref);
        W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, x_offset);
        W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, y_offset);
        W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, z_offset);
    }
    else if (res == -1){
        W_SET_PANELITEM_ARGS(Ladder_Position_Xref, W_PANEL_VALUE, "Unset");
        W_SET_PANELITEM_ARGS(Ladder_Position_Yref, W_PANEL_VALUE, "Unset");
        W_SET_PANELITEM_ARGS(Ladder_Position_Zref, W_PANEL_VALUE, "Unset");
        W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, 0);
        W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, 0);
        W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, 0); 
        U_CONFIRM("参考坐标系定义不正确");
    }   
    return(0);
}

create_material_panel(mainform)
{
    /* 创建用于显示直梯材料信息的面板 */
    Material = W_ADD_WINDOW(mainform, W_PANEL, "Material");
   
    /* 设置面板参数 */
	W_REALIZE_WINDOW(Material, 	W_FRAME_X, 		465,
							    W_FRAME_Y, 		135,
							    W_FRAME_WIDTH, 	400,
							    W_FRAME_HEIGHT,	50);
							            
    title = W_ADD_PANELITEM(Material, W_PANEL_MESSAGE, "title");
    W_REALIZE_PANELITEM(title, W_PANEL_ROW,	0,
		                       W_PANEL_COL,	0,
		                       W_PANEL_LABEL,	"直梯材料");
                               
    seperate_line = W_ADD_PANELITEM(Material, W_PANEL_MESSAGE, "seperate_line");
    W_REALIZE_PANELITEM(seperate_line,  W_PANEL_ROW, 0,
	                                    W_PANEL_COL, 7,
		                                W_PANEL_LABEL,	"",
		                                W_PANEL_SEPARATOR, 1);
									       
	Ladder_Part1 = W_ADD_PANELITEM(Material, W_PANEL_FILL, "Ladder_Part1");	
	W_REALIZE_PANELITEM(Ladder_Part1,  W_PANEL_ROW, 1, 
	                                   W_PANEL_COL, 0,
							           W_PANEL_LABEL, "扁钢:   ",
							           W_PANEL_LENGTH, 100,
							           W_PANEL_DISPLEN, 26,
							           W_PANEL_VALUE, "Undefined");  
							               	
	Select_Ladder_Part1 = W_ADD_PANELITEM(Material, W_PANEL_BUTTON, "Select_Ladder_Part1");	
	W_REALIZE_PANELITEM(Select_Ladder_Part1,  W_PANEL_ROW, 1, 
	                                          W_PANEL_COL, 34,
                  							  W_PANEL_BUTTONIMAGE, "选择扁钢", 
                  							  W_PANEL_WIDTH, 10,
                  							  W_PANEL_BUTTONVALUE, 201,
                  							  W_PANEL_CALLBACK, 1,
                  							  W_PANEL_LAYOUT, W_LAYOUT_HORIZONTAL);	                  							
    W_SET_PANELITEM_HANDLER(Select_Ladder_Part1, "select_ladder_part1_handler"); 			

	Ladder_Part2 = W_ADD_PANELITEM(Material, W_PANEL_FILL, "Ladder_Part2");	
	W_REALIZE_PANELITEM(Ladder_Part2, W_PANEL_ROW, 2, 
	                                  W_PANEL_COL, 0,
							          W_PANEL_LABEL, "踏步:   ",
							          W_PANEL_LENGTH, 100,
							          W_PANEL_DISPLEN, 26,
							          W_PANEL_VALUE, "Undefined"); 
	
	Select_Ladder_Part2 = W_ADD_PANELITEM(Material, W_PANEL_BUTTON, "Select_Ladder_Part2");	
	W_REALIZE_PANELITEM(Select_Ladder_Part2, W_PANEL_ROW, 2, 
	                                         W_PANEL_COL, 34,
                  						     W_PANEL_BUTTONIMAGE, "选择方钢", 
                     					     W_PANEL_WIDTH, 10,
                                             W_PANEL_BUTTONVALUE, 202,
                                             W_PANEL_CALLBACK, 1,
                     					     W_PANEL_LAYOUT, W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Select_Ladder_Part2, "select_ladder_part2_handler"); 	
   
	Ladder_Part3 = W_ADD_PANELITEM(Material, W_PANEL_FILL, "Ladder_Part3");	
	W_REALIZE_PANELITEM(Ladder_Part3,  W_PANEL_ROW, 3, 
	                                   W_PANEL_COL, 0,
							           W_PANEL_LABEL, "螺栓:   ",
							           W_PANEL_LENGTH, 26,
							           W_PANEL_VALUE, "Undefined",
							           W_PANEL_CALLBACK, 1);							             
	W_SET_PANELITEM_HANDLER(Ladder_Part3, "ladder_part3_handler"); 
	
	Select_Ladder_Part3 = W_ADD_PANELITEM(Material, W_PANEL_BUTTON, "Select_Ladder_Part3");	
	W_REALIZE_PANELITEM(Select_Ladder_Part3,  W_PANEL_ROW, 3, 
	                                          W_PANEL_COL, 34,
                  						      W_PANEL_BUTTONIMAGE, "选择螺栓", 
                  						      W_PANEL_WIDTH, 10,
                  						      W_PANEL_BUTTONVALUE, 203,
                  						      W_PANEL_CALLBACK, 0,
                  						      W_PANEL_LAYOUT, W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Select_Ladder_Part3, "select_ladder_part3_handler");

	Ladder_Part4 = W_ADD_PANELITEM(Material, W_PANEL_FILL, "Ladder_Part4");	
	W_REALIZE_PANELITEM(Ladder_Part4,  W_PANEL_ROW, 4, 
	                                   W_PANEL_COL, 0,
							           W_PANEL_LABEL, "螺母:   ",
							           W_PANEL_LENGTH, 26,
							           W_PANEL_VALUE, "Undefined",
							           W_PANEL_CALLBACK, 1);							             
	W_SET_PANELITEM_HANDLER(Ladder_Part4, "ladder_part4_handler"); 
	
	Select_Ladder_Part4 = W_ADD_PANELITEM(Material, W_PANEL_BUTTON, "Select_Ladder_Part4");	
	W_REALIZE_PANELITEM(Select_Ladder_Part4,  W_PANEL_ROW, 4, 
	                                          W_PANEL_COL, 34,
                  						      W_PANEL_BUTTONIMAGE, "选择螺母", 
                  						      W_PANEL_WIDTH, 10,
                  						      W_PANEL_BUTTONVALUE, 203,
                  						      W_PANEL_CALLBACK, 0,
                  						      W_PANEL_LAYOUT, W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Select_Ladder_Part4, "select_ladder_part4_handler");

	Ladder_Part5 = W_ADD_PANELITEM(Material, W_PANEL_FILL, "Ladder_Part5");	
	W_REALIZE_PANELITEM(Ladder_Part5,  W_PANEL_ROW, 5, 
	                                   W_PANEL_COL, 0,
							           W_PANEL_LABEL, "垫圈:   ",
							           W_PANEL_LENGTH, 26,
							           W_PANEL_VALUE, "Undefined",
							           W_PANEL_CALLBACK, 1);							             
	W_SET_PANELITEM_HANDLER(Ladder_Part5, "ladder_part5_handler"); 
	
	Select_Ladder_Part5 = W_ADD_PANELITEM(Material, W_PANEL_BUTTON, "Select_Ladder_Part5");	
	W_REALIZE_PANELITEM(Select_Ladder_Part5,  W_PANEL_ROW, 5, 
	                                          W_PANEL_COL, 34,
                  						      W_PANEL_BUTTONIMAGE, "选择垫圈", 
                  						      W_PANEL_WIDTH, 10,
                  						      W_PANEL_BUTTONVALUE, 203,
                  						      W_PANEL_CALLBACK, 0,
                  						      W_PANEL_LAYOUT, W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Select_Ladder_Part5, "select_ladder_part5_handler");
    
	Ladder_Part6 = W_ADD_PANELITEM(Material, W_PANEL_FILL, "Ladder_Part6");	
	W_REALIZE_PANELITEM(Ladder_Part6,  W_PANEL_ROW, 6, 
	                                   W_PANEL_COL, 0,
							           W_PANEL_LABEL, "垫板:   ",
							           W_PANEL_LENGTH, 26,
							           W_PANEL_VALUE, "Undefined",
							           W_PANEL_CALLBACK, 1);							             
	W_SET_PANELITEM_HANDLER(Ladder_Part6, "ladder_part6_handler"); 
	
	Select_Ladder_Part6 = W_ADD_PANELITEM(Material, W_PANEL_BUTTON, "Select_Ladder_Part4");	
	W_REALIZE_PANELITEM(Select_Ladder_Part6,  W_PANEL_ROW, 6, 
	                                          W_PANEL_COL, 34,
                  						      W_PANEL_BUTTONIMAGE, "选择钢板", 
                  						      W_PANEL_WIDTH, 10,
                  						      W_PANEL_BUTTONVALUE, 203,
                  						      W_PANEL_CALLBACK, 0,
                  						      W_PANEL_LAYOUT, W_LAYOUT_HORIZONTAL);	
    W_SET_PANELITEM_HANDLER(Select_Ladder_Part6, "select_ladder_part6_handler");

    Ladder_Bolt_Switch = W_ADD_PANELITEM(Material, W_PANEL_TOGGLE, "Ladder_Bolt_Switch");
	W_REALIZE_PANELITEM(Ladder_Bolt_Switch,  W_PANEL_ROW,            7,
	                                         W_PANEL_COL,            0,
                     						 W_PANEL_LABEL,          "",
                     						 W_PANEL_CHOICESTRING,   "螺栓  ",
                     						 W_PANEL_VALUE,          "1",
                     						 W_PANEL_CHOICESTYLE,    W_STYLE_PUSHBUTTONS,
                     						 W_PANEL_CALLBACK,       1);
    W_SET_PANELITEM_HANDLER(Ladder_Bolt_Switch, "ladder_bolt_switch_handler");

    Ladder_Nut_Switch = W_ADD_PANELITEM(Material, W_PANEL_TOGGLE, "Ladder_Nut_Switch");
	W_REALIZE_PANELITEM(Ladder_Nut_Switch,  W_PANEL_ROW,            7,
	                                        W_PANEL_COL,            8,
                     						W_PANEL_LABEL,          "",
                     						W_PANEL_CHOICESTRING,   "螺母  ",
                     						W_PANEL_VALUE,          "1",
                     						W_PANEL_CHOICESTYLE,    W_STYLE_PUSHBUTTONS,
                     						W_PANEL_CALLBACK,       1);
    W_SET_PANELITEM_HANDLER(Ladder_Nut_Switch, "ladder_nut_switch_handler");
    
    Ladder_Washer_Switch = W_ADD_PANELITEM(Material, W_PANEL_TOGGLE, "Ladder_Washer_Switch");
	W_REALIZE_PANELITEM(Ladder_Washer_Switch,  W_PANEL_ROW,            7,
	                                           W_PANEL_COL,            16,
                                               W_PANEL_LABEL,          "",
                     						   W_PANEL_CHOICESTRING,   "垫圈  ",
                     						   W_PANEL_VALUE,          "1",
                     						   W_PANEL_CHOICESTYLE,    W_STYLE_PUSHBUTTONS,
                     						   W_PANEL_CALLBACK,       1);
    W_SET_PANELITEM_HANDLER(Ladder_Washer_Switch, "ladder_washer_switch_handler");
    
    Ladder_Pad_Switch = W_ADD_PANELITEM(Material, W_PANEL_TOGGLE, "Ladder_Pad_Switch");
	W_REALIZE_PANELITEM(Ladder_Pad_Switch,  W_PANEL_ROW,            7,
	                                        W_PANEL_COL,            24,
                     						W_PANEL_LABEL,          "",
                     						W_PANEL_CHOICESTRING,   "垫板  ",
                     						W_PANEL_VALUE,          "1",
                     						W_PANEL_CHOICESTYLE,    W_STYLE_PUSHBUTTONS,
                     						W_PANEL_CALLBACK,       1);
    W_SET_PANELITEM_HANDLER(Ladder_Pad_Switch, "ladder_pad_switch_handler");
    
    return(Material);
}

ladder_bolt_switch_handler(item, event_type, dummy)
{
    res = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
	ladder_bolt_switch(res);
}

ladder_bolt_switch(flag)
{
	if(flag=="0"){
        W_SET_PANELITEM_ARGS(Ladder_Part3, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Select_Ladder_Part3, W_PANEL_SENSITIVITY,0);
        Bolt_Switch = "off";
        SET_STRING_DEFAULT("StraightLadder102", "Bolt_Switch", "off");
	}
	else if(flag=="1"){
	    W_SET_PANELITEM_ARGS(Ladder_Part3, W_PANEL_SENSITIVITY,1);
	    W_SET_PANELITEM_ARGS(Select_Ladder_Part3, W_PANEL_SENSITIVITY,1);
	    Bolt_Switch = "on";
	    SET_STRING_DEFAULT("StraightLadder102", "Bolt_Switch", "on");
	}
    if(Modify_flag){
        st = PM_UM_OPEN_CHANGE("修改直梯螺栓");
        calculate_ladder_para();
        delete_ladder_members();
        res = create_ladder(); 
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }  
        st = PM_UM_CLOSE_CHANGE();
    }
}

ladder_nut_switch_handler(item, event_type, dummy)
{
    res = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
	ladder_nut_switch(res);
}

ladder_nut_switch(flag)
{
	if(flag=="0"){
        W_SET_PANELITEM_ARGS(Ladder_Part4, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Select_Ladder_Part4, W_PANEL_SENSITIVITY,0);
        Nut_Switch = "off";
        SET_STRING_DEFAULT("StraightLadder102", "Nut_Switch", "off");
	}
	else if(flag=="1"){
	    W_SET_PANELITEM_ARGS(Ladder_Part4, W_PANEL_SENSITIVITY,1);
	    W_SET_PANELITEM_ARGS(Select_Ladder_Part4, W_PANEL_SENSITIVITY,1);
	    Nut_Switch = "on";
	    SET_STRING_DEFAULT("StraightLadder102", "Nut_Switch", "on");
	}
    if(Modify_flag){
        st = PM_UM_OPEN_CHANGE("修改直梯螺栓螺母");
        calculate_ladder_para();
        delete_ladder_members();
        res = create_ladder(); 
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }  
        st = PM_UM_CLOSE_CHANGE();
    }
}

ladder_washer_switch_handler(item, event_type, dummy)
{
    res = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
	ladder_washer_switch(res);
}

ladder_washer_switch(flag)
{
	if(flag=="0"){
        W_SET_PANELITEM_ARGS(Ladder_Part5, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Select_Ladder_Part5, W_PANEL_SENSITIVITY,0);
        Washer_Switch = "off";
        SET_STRING_DEFAULT("StraightLadder102", "Washer_Switch", "off");
	}
	else if(flag=="1"){
	    W_SET_PANELITEM_ARGS(Ladder_Part5, W_PANEL_SENSITIVITY,1);
	    W_SET_PANELITEM_ARGS(Select_Ladder_Part5, W_PANEL_SENSITIVITY,1);
	    Washer_Switch = "on";
	    SET_STRING_DEFAULT("StraightLadder102", "Washer_Switch", "on");
	}
    if(Modify_flag){
        st = PM_UM_OPEN_CHANGE("修改直梯垫圈");
        calculate_ladder_para();
        delete_ladder_members();
        res = create_ladder(); 
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }  
        st = PM_UM_CLOSE_CHANGE();
    }
}

ladder_pad_switch_handler(item, event_type, dummy)
{
    res = W_GET_PANELITEM_ARG(item, W_PANEL_VALUE);
	ladder_pad_switch(res);
}

ladder_pad_switch(flag)
{
	if(flag=="0"){
        W_SET_PANELITEM_ARGS(Ladder_Para_a, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Ladder_Para_b, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Ladder_Para_r, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Ladder_Part6, W_PANEL_SENSITIVITY,0);
        W_SET_PANELITEM_ARGS(Select_Ladder_Part6, W_PANEL_SENSITIVITY,0);
        Pad_Switch = "off";
        SET_STRING_DEFAULT("StraightLadder102", "Pad_Switch", "off");
	}
	else if(flag=="1"){
        W_SET_PANELITEM_ARGS(Ladder_Para_a, W_PANEL_SENSITIVITY,1);
        W_SET_PANELITEM_ARGS(Ladder_Para_b, W_PANEL_SENSITIVITY,1);
        W_SET_PANELITEM_ARGS(Ladder_Para_r, W_PANEL_SENSITIVITY,1);
	    W_SET_PANELITEM_ARGS(Ladder_Part6, W_PANEL_SENSITIVITY,1);
	    W_SET_PANELITEM_ARGS(Select_Ladder_Part6, W_PANEL_SENSITIVITY,1);
	    Pad_Switch = "on";
	    SET_STRING_DEFAULT("StraightLadder102", "Pad_Switch", "on");
	}
    if(Modify_flag){
        st = PM_UM_OPEN_CHANGE("修改直梯垫板");
        calculate_ladder_para();
        delete_ladder_members();
        res = create_ladder(); 
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }  
        st = PM_UM_CLOSE_CHANGE();
    }
}

ladder_part1_handler(item, event_type, dummy)
{	
	pid = Ladder_Part1_Pid;
	if(ISSTRING(pid)){
		if(!Is_Equal_Angle_Bar(pid)){
			beam_descr = Pid_To_Description(pid);
			W_SET_PANELITEM_ARGS(Ladder_Part1, W_PANEL_VALUE, beam_descr);
			SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part1", pid);
		}
	}	
	return(0);
}

ladder_part2_handler(item, event_type, dummy)
{
	pid = Ladder_Part2_Pid;
	if(ISSTRING(pid)){
        
		if(Is_Equal_Angle_Bar(pid)){
			beam_descr = Pid_To_Description(pid);
			W_SET_PANELITEM_ARGS(Ladder_Part1, W_PANEL_VALUE, beam_descr);
			SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part2", pid);
		}
	}	
	return(0); 
}

ladder_part3_handler(item, event_type, dummy)
{
   return(0);
}

ladder_part4_handler(item, event_type, dummy)
{
   return(0);
}

ladder_part5_handler(item, event_type, dummy)
{
   return(0);
}

ladder_part6_handler(item, event_type, dummy)
{
   return(0);
}

select_ladder_part1_handler(item, event_type, button_value)
{
	U_MESSAGE("选择扶手的材料(扁钢)");
	selectmask = DM_INIT_TAGREC();
	DM_SET_TAGVAL(selectmask, "KW", "BEAM Flat*");	
	pid = DM_BROWSE_PARTCODE(Ladder_Part1_Pid, 1, selectmask);
	if(ISSTRING(pid)){
		Ladder_Part1_Pid = pid;
		descr = Pid_To_Description(pid);
		W_SET_PANELITEM_ARGS(Ladder_Part1, W_PANEL_VALUE, descr);
		SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part1", pid);
	}	
	if(Modify_flag){
        /* 定义UNDO缓存 */
        st = PM_UM_OPEN_CHANGE("重新选择扁钢");
        delete_ladder_members();
        calculate_ladder_para();
        res = create_ladder();
        /* 如果修改不成功，回滚到原来状态 */
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }           
        st = PM_UM_CLOSE_CHANGE(); 	   
	}
	return(0); 
}

select_ladder_part2_handler(item, event_type, button_value)
{
	U_MESSAGE("选择踏步的材料(方钢)");
	selectmask = DM_INIT_TAGREC();
	DM_SET_TAGVAL(selectmask, "KW", "BEAM RHS*");
	pid = DM_BROWSE_PARTCODE(Ladder_Part2_Pid, 1, selectmask);
	if(ISSTRING(pid)){
		Ladder_Part2_Pid = pid;
		descr = Pid_To_Description(pid);
		W_SET_PANELITEM_ARGS(Ladder_Part2, W_PANEL_VALUE, descr);
		SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part2", pid);
	}
	if(Modify_flag){
        /* 定义UNDO缓存 */
        st = PM_UM_OPEN_CHANGE("重新选择踏步材料");
        delete_ladder_members();
        calculate_ladder_para();
        res = create_ladder();
        /* 如果修改不成功，回滚到原来状态 */
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }
        st = PM_UM_CLOSE_CHANGE();
	}
	return(0); 
}

select_ladder_part3_handler(item, event_type, button_value)
{
	U_MESSAGE("选择螺栓(有几何体)");
	selectmask = DM_INIT_TAGREC();
	DM_SET_TAGVAL(selectmask, "KW", "BOLT*");
	pid = DM_BROWSE_PARTCODE(Ladder_Part3_Pid, 1, selectmask);
	if(ISSTRING(pid)){
        /* wei = DM_PARTID_DATA(pid,"D61"); */
        /* sor = DM_PARTID_DATA(pid,"sor"); */
        Ladder_Part3_Pid = pid;
        descr = Pid_To_Description(pid);
        W_SET_PANELITEM_ARGS(Ladder_Part3, W_PANEL_VALUE, descr);
        SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part3", pid);
	}	
	if(Modify_flag){
        /* 定义UNDO缓存 */
        st = PM_UM_OPEN_CHANGE("重新选择螺栓");
        delete_ladder_members();
        calculate_ladder_para();
        res = create_ladder();
        /* 如果修改不成功，回滚到原来状态 */
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }           
        st = PM_UM_CLOSE_CHANGE(); 	   
	}
	return(0);
}

select_ladder_part4_handler(item, event_type, button_value)
{
	U_MESSAGE("选择螺母(有几何体)");
	selectmask = DM_INIT_TAGREC();
	DM_SET_TAGVAL(selectmask, "KW", "NUT*");	
	pid = DM_BROWSE_PARTCODE(Ladder_Part4_Pid, 1, selectmask);
	if(ISSTRING(pid)){
		Ladder_Part4_Pid = pid;
		descr = Pid_To_Description(pid);
		W_SET_PANELITEM_ARGS(Ladder_Part4, W_PANEL_VALUE, descr);
		SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part4", pid);
	}
	if(Modify_flag){
        /* 定义UNDO缓存 */
        st = PM_UM_OPEN_CHANGE("重新选择螺母");
        delete_ladder_members();
        calculate_ladder_para();
        res = create_ladder();
        /* 如果修改不成功，回滚到原来状态 */
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }           
        st = PM_UM_CLOSE_CHANGE(); 	   
	}
	return(0); 
}

select_ladder_part5_handler(item, event_type, button_value)
{
	U_MESSAGE("选择垫圈(有几何体)");
	selectmask = DM_INIT_TAGREC();
	DM_SET_TAGVAL(selectmask, "KW", "WASHER*");	
	pid = DM_BROWSE_PARTCODE(Ladder_Part5_Pid, 1, selectmask);
	if(ISSTRING(pid)){
		Ladder_Part5_Pid = pid;
		descr = Pid_To_Description(pid);
		W_SET_PANELITEM_ARGS(Ladder_Part5, W_PANEL_VALUE, descr);
		SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part5", pid);
	}	
	if(Modify_flag){
        /* 定义UNDO缓存 */
        st = PM_UM_OPEN_CHANGE("重新选择垫圈");
        delete_ladder_members();
        calculate_ladder_para();
        res = create_ladder();
        /* 如果修改不成功，回滚到原来状态 */
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }           
        st = PM_UM_CLOSE_CHANGE(); 	   
	}
	return(0); 
}

select_ladder_part6_handler(item, event_type, button_value)
{
	U_MESSAGE("选择垫板材料(钢板)");
	selectmask = DM_INIT_TAGREC();
	DM_SET_TAGVAL(selectmask, "KW", "PLATE*");
	pid = DM_BROWSE_PARTCODE(Ladder_Part6_Pid, 1, selectmask);
	if(ISSTRING(pid)){
        Ladder_Part6_Pid = pid;
        pad_descr = Pid_To_Description(pid);
        W_SET_PANELITEM_ARGS(Ladder_Part6, W_PANEL_VALUE, pad_descr);
        SET_STRING_DEFAULT("StraightLadder102", "Ladder_Part6", pid);
	}	
	if(Modify_flag){
        st = PM_UM_OPEN_CHANGE("修改垫板材料");
        delete_ladder_members();  
        calculate_ladder_para();            
        res = create_ladder();
        /* 如果修改不成功，回滚到原来状态 */
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }
        st = PM_UM_CLOSE_CHANGE(); 	   	   
	}
	return(0);
}

create_ladder_handler(item, event_type, button_value)
{
    /* 获取直梯名称 */
    Info_Ladder_Name = W_GET_PANELITEM_ARG(Ladder_Name, W_PANEL_VALUE);     
    if (Info_Ladder_Name == "Undefined"){
        U_CONFIRM("请先输入直梯编号");
        return(0);
    }

    /* 定义UNDO缓存 */
    st = PM_UM_OPEN_CHANGE("创建直梯" + Info_Ladder_Name);

    /* 定义直梯组 */  
    group_h = Create_Group(Group_Type, Info_Ladder_Name);
    if(ISINT(group_h)){
        U_CONFIRM("无法创建直梯模型组，请检查是否已经定义了这种类型的模型组？");
        st = PM_UM_CLOSE_CHANGE();
        PM_UM_UNDO_LAST_CHANGE();
        return(0);
    } 
   
    Ladder_Handle = group_h; 
   
    /* 选择创建的平面 */
	x0 = 0;y0 = 0;z0 = 0;
	trace_handle = PM_NEW_TRACEP();  
	PM_GET_CURRENT_LOC(x0,y0,z0);  
	res = PM_GET_POINT("请选择直梯位置", trace_handle, x0, y0, z0); 
	if( res < 0 ){
        st = PM_UM_CLOSE_CHANGE();
        PM_UM_UNDO_LAST_CHANGE();   
		return(0);
	}
    
    Ladder_X0 = x0; 
    Ladder_Y0 = y0;
    Ladder_Z0 = z0;
	W_SET_NUMERIC_VALUE(Ladder_Position_X, x0);
	W_SET_NUMERIC_VALUE(Ladder_Position_Y, y0);
	W_SET_NUMERIC_VALUE(Ladder_Position_Z, z0);
	trans_abs_ref();
    
    /* 计算直梯参数 */
    res = calculate_ladder_para(); 
    if(res == -1){
        U_CONFIRM("无法创建直梯模型组，请检查直梯参数是否正确？");
        st = PM_UM_CLOSE_CHANGE();
        PM_UM_UNDO_LAST_CHANGE();      
        return(0);
    }
    
    /* 创建直梯，如创建不成功，删除相关定义 */
    res = create_ladder();
    if (res == -1){
        PM_UM_CLOSE_CHANGE();
        PM_UM_UNDO_LAST_CHANGE();
        return(0);
    }
    st = PM_UM_CLOSE_CHANGE();
   
    /*直梯创建成功，进入修改状态*/
	W_SET_PANELITEM_ARGS(Create_Ladder, W_PANEL_SENSITIVITY,0);
	Modify_flag = 1;
}

/*计算复制直梯踏步数量*/
calculate_ladder_step_count()
{
    int copy_count;
    copy_count = 0;
    step_length = Ladder_Size_L - Ladder_Size_h1 - Ladder_Size_h2;
    if(step_length<2*Ladder_Size_h){
        return(copy_count);
    }
    flag = (step_length+1) / Ladder_Size_h;
    copy_count = SCAN_QUANT(3,FTOASCII(flag));
    copy_count = copy_count - 1; 
    return(copy_count);
}

calculate_ladder_para()
{  
    /* 检查是否已经选择了所需的零件 */
    handle_part_1 = W_GET_PANELITEM_ARG(Ladder_Part1, W_PANEL_VALUE);
    if (handle_part_1 == "Undefined"){
        U_CONFIRM("请先选择扶手材料");
        return(-1);
    }

    handle_part_2 = W_GET_PANELITEM_ARG(Ladder_Part2, W_PANEL_VALUE);
    if (handle_part_2 == "Undefined"){
        U_CONFIRM("请先选择踏步材料");
        return(-1);
    }
    
    if(Bolt_Switch=="on"){
        handle_part_3 = W_GET_PANELITEM_ARG(Ladder_Part3, W_PANEL_VALUE);
        if (handle_part_3 == "Undefined"){
            U_CONFIRM("请先选择螺栓材料");
            return(-1);
        }
    }
  
    if(Nut_Switch=="on"){
        handle_part_4 = W_GET_PANELITEM_ARG(Ladder_Part4, W_PANEL_VALUE);
        if (handle_part_4 == "Undefined"){
            U_CONFIRM("请先选择螺母材料");
            return(-1);
        }
    }
    
    if(Washer_Switch=="on"){
        handle_part_5 = W_GET_PANELITEM_ARG(Ladder_Part5, W_PANEL_VALUE);
        if (handle_part_5 == "Undefined"){
            U_CONFIRM("请先选择垫圈材料");
            return(-1);
        }
    }
    
    if(Pad_Switch=="on"){
        handle_part_6 = W_GET_PANELITEM_ARG(Ladder_Part6, W_PANEL_VALUE);
        if (handle_part_6 == "Undefined"){
            U_CONFIRM("请先选择垫板材料");
            return(-1);
        }
    }
    
    /* 获取直梯位置坐标 */
    st = 0;
    x0 = W_GET_NUMERIC_VALUE(Ladder_Position_X, st);
    if (st == -1){
        U_CONFIRM("X坐标未定义");
        return(-1);
    }
    Ladder_X0 = x0;
   
    st = 0;
    y0 = W_GET_NUMERIC_VALUE(Ladder_Position_Y, st);
    if (st == -1){
        U_CONFIRM("Y坐标未定义");
        return(-1);
    }
    Ladder_Y0 = y0;
   
    st = 0;
    z0 = W_GET_NUMERIC_VALUE(Ladder_Position_Z, st); 
    if (st == -1){
        U_CONFIRM("Z坐标未定义");
        return(-1);
    }
    Ladder_Z0 = z0;   
      
    /* 获取直梯尺寸 */
    st = 0;
    Ladder_Size_L = W_GET_NUMERIC_VALUE(Ladder_Para_L, st);
    if (st == -1){
        U_MESSAGE("无法获取参数L的值或者L的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_W = W_GET_NUMERIC_VALUE(Ladder_Para_W, st);
    if (st == -1){
        U_MESSAGE("无法获取参数W的值或者W的值有错误");
        return(-1);
    }   
   
    st = 0;
    Ladder_Size_h = W_GET_NUMERIC_VALUE(Ladder_Para_h, st);
    if (st == -1){
        U_MESSAGE("无法获取参数h的值或者h的值有错误");
        return(-1);
    }   

    st = 0;
    Ladder_Size_h1 = W_GET_NUMERIC_VALUE(Ladder_Para_h1, st);
    if (st == -1){
        U_MESSAGE("无法获取参数h1的值或者h1的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_h2 = W_GET_NUMERIC_VALUE(Ladder_Para_h2, st);
    if (st == -1){
        U_MESSAGE("无法获取参数h2的值或者h2的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_d1 = W_GET_NUMERIC_VALUE(Ladder_Para_d1, st);
    if (st == -1){
        U_MESSAGE("无法获取参数d1的值或者d1的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_d2 = W_GET_NUMERIC_VALUE(Ladder_Para_d2, st);
    if (st == -1){
        U_MESSAGE("无法获取参数d2的值或者d2的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_a = W_GET_NUMERIC_VALUE(Ladder_Para_a, st);
    if (st == -1){
        U_MESSAGE("无法获取参数a的值或者a的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_b = W_GET_NUMERIC_VALUE(Ladder_Para_b, st);
    if (st == -1){
        U_MESSAGE("无法获取参数b的值或者b的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_r = W_GET_NUMERIC_VALUE(Ladder_Para_r, st);
    if (st == -1){
        U_MESSAGE("无法获取参数r的值或者r的值有错误");
        return(-1);
    }

    st = 0;
    Ladder_Size_ad = W_GET_NUMERIC_VALUE(Ladder_Para_ad, st);
    if (st == -1){
        U_MESSAGE("无法获取参数ad的值或者ad的值有错误");
        return(-1);
    }
    
    st = 0;
    Ladder_Size_bd = W_GET_NUMERIC_VALUE(Ladder_Para_bd, st);
    if (st == -1){
        U_MESSAGE("无法获取参数bd的值或者bd的值有错误");
        return(-1);
    }
    
    /* 获取零件参数 */
    flatbar_width = 1.0*DM_PARTID_DATA(Ladder_Part1_Pid, "D31");
    flatbar_thick = 1.0*DM_PARTID_DATA(Ladder_Part1_Pid, "D32");
    if(Pad_Switch == "on"){
        pad_plate_thick = 1.0*DM_PARTID_DATA(Ladder_Part6_Pid, "D31");
    }
    else{
        pad_plate_thick = 0.0;
    }
    if(Washer_Switch == "on"){
        washer_plate_thick = 1.0*DM_PARTID_DATA(Ladder_Part5_Pid, "D31");
    }
    else{
        washer_plate_thick = 0.0;
    }
    
    zdx = 0;zdy = 0;zdz = 0;
    VEC_CROSS_PRODUCT(Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz, zdx,zdy,zdz);
    VEC_UNITV(zdx,zdy,zdz);
   
    /*计算零件1-1相关参数 calculate parameter of part1-1*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + 0.5*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);  
        distance = -Ladder_Size_h1;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = Ladder_Size_L;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx = Ladder_X_Dx;
        x_dy = Ladder_X_Dy;
        x_dz = Ladder_X_Dz;
        end1x = -zdx;
        end1y = -zdy;
        end1z = -zdz;
        end2x = zdx;
        end2y = zdy;
        end2z = zdz;

        A_PUT(Part11,0,x1);
        A_PUT(Part11,1,y1);
        A_PUT(Part11,2,z1);
        A_PUT(Part11,3,x2);
        A_PUT(Part11,4,y2);
        A_PUT(Part11,5,z2);
        A_PUT(Part11,6,x_dx);
        A_PUT(Part11,7,x_dy);
        A_PUT(Part11,8,x_dz);
        A_PUT(Part11,9,end1x);
        A_PUT(Part11,10,end1y);
        A_PUT(Part11,11,end1z);
        A_PUT(Part11,12,end2x);
        A_PUT(Part11,13,end2y);
        A_PUT(Part11,14,end2z);	
    }
   
    /*计算零件1-2相关参数 calculate parameter of part1-2*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -Ladder_Size_W/2 - 0.5*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);  
        distance = -Ladder_Size_h1;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = Ladder_Size_L;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx = -Ladder_X_Dx;
        x_dy = -Ladder_X_Dy;
        x_dz = -Ladder_X_Dz;
        end1x = -zdx;
        end1y = -zdy;
        end1z = -zdz;
        end2x = zdx;
        end2y = zdy;
        end2z = zdz;

        A_PUT(Part12,0,x1);
        A_PUT(Part12,1,y1);
        A_PUT(Part12,2,z1);
        A_PUT(Part12,3,x2);
        A_PUT(Part12,4,y2);
        A_PUT(Part12,5,z2);
        A_PUT(Part12,6,x_dx);
        A_PUT(Part12,7,x_dy);
        A_PUT(Part12,8,x_dz);
        A_PUT(Part12,9,end1x);
        A_PUT(Part12,10,end1y);
        A_PUT(Part12,11,end1z);
        A_PUT(Part12,12,end2x);
        A_PUT(Part12,13,end2y);
        A_PUT(Part12,14,end2z);	
    } 
    
    /*计算零件1-3相关参数 calculate parameter of part1-3*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + 1.5*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1 - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);  
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = Ladder_Size_d1 - pad_plate_thick + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx  = Ladder_X_Dx;
        x_dy  = Ladder_X_Dy;
        x_dz  = Ladder_X_Dz;
        end1x = -Ladder_Y_Dx;
        end1y = -Ladder_Y_Dy;
        end1z = -Ladder_Y_Dz;
        end2x = Ladder_Y_Dx;
        end2y = Ladder_Y_Dy;
        end2z = Ladder_Y_Dz;

        A_PUT(Part13,0,x1);
        A_PUT(Part13,1,y1);
        A_PUT(Part13,2,z1);
        A_PUT(Part13,3,x2);
        A_PUT(Part13,4,y2);
        A_PUT(Part13,5,z2);
        A_PUT(Part13,6,x_dx);
        A_PUT(Part13,7,x_dy);
        A_PUT(Part13,8,x_dz);
        A_PUT(Part13,9,end1x);
        A_PUT(Part13,10,end1y);
        A_PUT(Part13,11,end1z);
        A_PUT(Part13,12,end2x);
        A_PUT(Part13,13,end2y);
        A_PUT(Part13,14,end2z);
    } 
   
    /*计算零件1-4相关参数 calculate parameter of part1-4*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -(Ladder_Size_W/2 + 1.5*flatbar_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1 - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);  
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = Ladder_Size_d1 - pad_plate_thick + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx  = Ladder_X_Dx;
        x_dy  = Ladder_X_Dy;
        x_dz  = Ladder_X_Dz;
        end1x = -Ladder_Y_Dx;
        end1y = -Ladder_Y_Dy;
        end1z = -Ladder_Y_Dz;
        end2x = Ladder_Y_Dx;
        end2y = Ladder_Y_Dy;
        end2z = Ladder_Y_Dz;

        A_PUT(Part14,0,x1);
        A_PUT(Part14,1,y1);
        A_PUT(Part14,2,z1);
        A_PUT(Part14,3,x2);
        A_PUT(Part14,4,y2);
        A_PUT(Part14,5,z2);
        A_PUT(Part14,6,x_dx);
        A_PUT(Part14,7,x_dy);
        A_PUT(Part14,8,x_dz);
        A_PUT(Part14,9,end1x);
        A_PUT(Part14,10,end1y);
        A_PUT(Part14,11,end1z);
        A_PUT(Part14,12,end2x);
        A_PUT(Part14,13,end2y);
        A_PUT(Part14,14,end2z);
    }

    /*计算零件1-5相关参数 calculate parameter of part1-5*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + flatbar_thick + 0.5*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1 - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);  
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = Ladder_Size_d2 - pad_plate_thick + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx  = Ladder_X_Dx;
        x_dy  = Ladder_X_Dy;
        x_dz  = Ladder_X_Dz;
        end1x = -Ladder_Y_Dx;
        end1y = -Ladder_Y_Dy;
        end1z = -Ladder_Y_Dz;
        end2x = Ladder_Y_Dx;
        end2y = Ladder_Y_Dy;
        end2z = Ladder_Y_Dz;

        A_PUT(Part15,0,x1);
        A_PUT(Part15,1,y1);
        A_PUT(Part15,2,z1);
        A_PUT(Part15,3,x2);
        A_PUT(Part15,4,y2);
        A_PUT(Part15,5,z2);
        A_PUT(Part15,6,x_dx);
        A_PUT(Part15,7,x_dy);
        A_PUT(Part15,8,x_dz);
        A_PUT(Part15,9,end1x);
        A_PUT(Part15,10,end1y);
        A_PUT(Part15,11,end1z);
        A_PUT(Part15,12,end2x);
        A_PUT(Part15,13,end2y);
        A_PUT(Part15,14,end2z);
    }    

    /*计算零件1-6相关参数 calculate parameter of part1-6*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -(Ladder_Size_W/2 + flatbar_thick + 0.5*flatbar_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1  - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);  
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = Ladder_Size_d2 - pad_plate_thick + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx = Ladder_X_Dx;
        x_dy = Ladder_X_Dy;
        x_dz = Ladder_X_Dz;
        end1x = -Ladder_Y_Dx;
        end1y = -Ladder_Y_Dy;
        end1z = -Ladder_Y_Dz;
        end2x = Ladder_Y_Dx;
        end2y = Ladder_Y_Dy;
        end2z = Ladder_Y_Dz;

        A_PUT(Part16,0,x1);
        A_PUT(Part16,1,y1);
        A_PUT(Part16,2,z1);
        A_PUT(Part16,3,x2);
        A_PUT(Part16,4,y2);
        A_PUT(Part16,5,z2);
        A_PUT(Part16,6,x_dx);
        A_PUT(Part16,7,x_dy);
        A_PUT(Part16,8,x_dz);
        A_PUT(Part16,9,end1x);
        A_PUT(Part16,10,end1y);
        A_PUT(Part16,11,end1z);
        A_PUT(Part16,12,end2x);
        A_PUT(Part16,13,end2y);
        A_PUT(Part16,14,end2z);
    }  
   
    /*计算零件2-1相关参数 calculate parameter of part2-1*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + flatbar_thick + Ladder_Size_Step_Extend;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        x1=x;y1=y;z1=z;

        distance = -2*(Ladder_Size_W/2 + flatbar_thick + Ladder_Size_Step_Extend);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx = Ladder_Y_Dx+zdx;
        x_dy = Ladder_Y_Dy+zdy;
        x_dz = Ladder_Y_Dz+zdz;
        end1x = Ladder_X_Dx;
        end1y = Ladder_X_Dy;
        end1z = Ladder_X_Dz;
        end2x = -Ladder_X_Dx;
        end2y = -Ladder_X_Dy;
        end2z = -Ladder_X_Dz;

        A_PUT(Part21,0,x1);
        A_PUT(Part21,1,y1);
        A_PUT(Part21,2,z1);
        A_PUT(Part21,3,x2);
        A_PUT(Part21,4,y2);
        A_PUT(Part21,5,z2);
        A_PUT(Part21,6,x_dx);
        A_PUT(Part21,7,x_dy);
        A_PUT(Part21,8,x_dz);
        A_PUT(Part21,9,end1x);
        A_PUT(Part21,10,end1y);
        A_PUT(Part21,11,end1z);
        A_PUT(Part21,12,end2x);
        A_PUT(Part21,13,end2y);
        A_PUT(Part21,14,end2z);
    }  
   
    /*计算零件2-2相关参数 calculate parameter of part2-2*/
    if(1){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + flatbar_thick + Ladder_Size_Step_Extend;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 - Ladder_Size_h2 + Ladder_Size_L;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);
        x1=x;y1=y;z1=z;

        distance = -2*(Ladder_Size_W/2 + flatbar_thick + Ladder_Size_Step_Extend);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        x2=x;y2=y;z2=z; 
        
        x_dx = Ladder_Y_Dx+zdx;
        x_dy = Ladder_Y_Dy+zdy;
        x_dz = Ladder_Y_Dz+zdz;
        end1x = Ladder_X_Dx;
        end1y = Ladder_X_Dy;
        end1z = Ladder_X_Dz;
        end2x = -Ladder_X_Dx;
        end2y = -Ladder_X_Dy;
        end2z = -Ladder_X_Dz;

        A_PUT(Part22,0,x1);
        A_PUT(Part22,1,y1);
        A_PUT(Part22,2,z1);
        A_PUT(Part22,3,x2);
        A_PUT(Part22,4,y2);
        A_PUT(Part22,5,z2);
        A_PUT(Part22,6,x_dx);
        A_PUT(Part22,7,x_dy);
        A_PUT(Part22,8,x_dz);
        A_PUT(Part22,9,end1x);
        A_PUT(Part22,10,end1y);
        A_PUT(Part22,11,end1z);
        A_PUT(Part22,12,end2x);
        A_PUT(Part22,13,end2y);
        A_PUT(Part22,14,end2z);
    }   

    /*计算零件3-1相关参数 calculate parameter of part3-1*/
    if(Bolt_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;
        distance = Ladder_Size_W/2;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   
     	
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part31,0,lox);
        A_PUT(Part31,1,loy);
        A_PUT(Part31,2,loz); 
        A_PUT(Part31,3,udx);
        A_PUT(Part31,4,udy);
        A_PUT(Part31,5,udz);  
        A_PUT(Part31,6,vdx);
        A_PUT(Part31,7,vdy);
        A_PUT(Part31,8,vdz);	
    } 

    /*计算零件3-2相关参数 calculate parameter of part3-2*/
    if(Bolt_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -Ladder_Size_W/2;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   
        
        lox = x;
        loy = y;
        loz = z;
        udx = -Ladder_X_Dx;
        udy = -Ladder_X_Dy;
        udz = -Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part32,0,lox);
        A_PUT(Part32,1,loy);
        A_PUT(Part32,2,loz); 
        A_PUT(Part32,3,udx);
        A_PUT(Part32,4,udy);
        A_PUT(Part32,5,udz);  
        A_PUT(Part32,6,vdx);
        A_PUT(Part32,7,vdy);
        A_PUT(Part32,8,vdz);	
    } 
    
    /*计算零件3-3相关参数 calculate parameter of part3-3*/
    if(Bolt_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   
        
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part33,0,lox);
        A_PUT(Part33,1,loy);
        A_PUT(Part33,2,loz); 
        A_PUT(Part33,3,udx);
        A_PUT(Part33,4,udy);
        A_PUT(Part33,5,udz);  
        A_PUT(Part33,6,vdx);
        A_PUT(Part33,7,vdy);
        A_PUT(Part33,8,vdz);	
    } 
    
    /*计算零件3-4相关参数 calculate parameter of part3-4*/
    if(Bolt_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -Ladder_Size_W/2;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);  
        
        lox = x;
        loy = y;
        loz = z;
        udx = -Ladder_X_Dx;
        udy = -Ladder_X_Dy;
        udz = -Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part34,0,lox);
        A_PUT(Part34,1,loy);
        A_PUT(Part34,2,loz); 
        A_PUT(Part34,3,udx);
        A_PUT(Part34,4,udy);
        A_PUT(Part34,5,udz);  
        A_PUT(Part34,6,vdx);
        A_PUT(Part34,7,vdy);
        A_PUT(Part34,8,vdz);	
    } 
    
    /*计算零件4-1相关参数 calculate parameter of part4-1*/
    if(Nut_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + 2*flatbar_thick + washer_plate_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part41,0,lox);
        A_PUT(Part41,1,loy);
        A_PUT(Part41,2,loz); 
        A_PUT(Part41,3,udx);
        A_PUT(Part41,4,udy);
        A_PUT(Part41,5,udz);  
        A_PUT(Part41,6,vdx);
        A_PUT(Part41,7,vdy);
        A_PUT(Part41,8,vdz);	
    } 
    
    /*计算零件4-2相关参数 calculate parameter of part4-2*/
    if(Nut_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -(Ladder_Size_W/2 + 2*flatbar_thick + washer_plate_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = -Ladder_X_Dx;
        udy = -Ladder_X_Dy;
        udz = -Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part42,0,lox);
        A_PUT(Part42,1,loy);
        A_PUT(Part42,2,loz); 
        A_PUT(Part42,3,udx);
        A_PUT(Part42,4,udy);
        A_PUT(Part42,5,udz);  
        A_PUT(Part42,6,vdx);
        A_PUT(Part42,7,vdy);
        A_PUT(Part42,8,vdz);	
    } 
    
    /*计算零件4-3相关参数 calculate parameter of part4-3*/
    if(Nut_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + 2*flatbar_thick + washer_plate_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part43,0,lox);
        A_PUT(Part43,1,loy);
        A_PUT(Part43,2,loz); 
        A_PUT(Part43,3,udx);
        A_PUT(Part43,4,udy);
        A_PUT(Part43,5,udz);  
        A_PUT(Part43,6,vdx);
        A_PUT(Part43,7,vdy);
        A_PUT(Part43,8,vdz);	
    } 
    
    /*计算零件4-4相关参数 calculate parameter of part4-4*/
    if(Nut_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -(Ladder_Size_W/2 + 2*flatbar_thick + washer_plate_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = -Ladder_X_Dx;
        udy = -Ladder_X_Dy;
        udz = -Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part44,0,lox);
        A_PUT(Part44,1,loy);
        A_PUT(Part44,2,loz); 
        A_PUT(Part44,3,udx);
        A_PUT(Part44,4,udy);
        A_PUT(Part44,5,udz);  
        A_PUT(Part44,6,vdx);
        A_PUT(Part44,7,vdy);
        A_PUT(Part44,8,vdz);	
    } 
    
    /*计算零件5-1相关参数 calculate parameter of part5-1*/
    if(Washer_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + 2*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part51,0,lox);
        A_PUT(Part51,1,loy);
        A_PUT(Part51,2,loz); 
        A_PUT(Part51,3,udx);
        A_PUT(Part51,4,udy);
        A_PUT(Part51,5,udz);  
        A_PUT(Part51,6,vdx);
        A_PUT(Part51,7,vdy);
        A_PUT(Part51,8,vdz);	
    } 
    
    /*计算零件5-2相关参数 calculate parameter of part5-2*/
    if(Washer_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -(Ladder_Size_W/2 + 2*flatbar_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = -Ladder_X_Dx;
        udy = -Ladder_X_Dy;
        udz = -Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part52,0,lox);
        A_PUT(Part52,1,loy);
        A_PUT(Part52,2,loz); 
        A_PUT(Part52,3,udx);
        A_PUT(Part52,4,udy);
        A_PUT(Part52,5,udz);  
        A_PUT(Part52,6,vdx);
        A_PUT(Part52,7,vdy);
        A_PUT(Part52,8,vdz);	
    }
    
    /*计算零件5-3相关参数 calculate parameter of part5-3*/
    if(Washer_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = Ladder_Size_W/2 + 2*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance); 
        
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part53,0,lox);
        A_PUT(Part53,1,loy);
        A_PUT(Part53,2,loz); 
        A_PUT(Part53,3,udx);
        A_PUT(Part53,4,udy);
        A_PUT(Part53,5,udz);  
        A_PUT(Part53,6,vdx);
        A_PUT(Part53,7,vdy);
        A_PUT(Part53,8,vdz);	
    }
    
    /*计算零件5-4相关参数 calculate parameter of part5-4*/
    if(Washer_Switch=="on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;    
        distance = -(Ladder_Size_W/2 + 2*flatbar_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);  
        
        lox = x;
        loy = y;
        loz = z;
        udx = -Ladder_X_Dx;
        udy = -Ladder_X_Dy;
        udz = -Ladder_X_Dz;
        vdx = Ladder_Y_Dx;
        vdy = Ladder_Y_Dy;
        vdz = Ladder_Y_Dz;
        A_PUT(Part54,0,lox);
        A_PUT(Part54,1,loy);
        A_PUT(Part54,2,loz); 
        A_PUT(Part54,3,udx);
        A_PUT(Part54,4,udy);
        A_PUT(Part54,5,udz);  
        A_PUT(Part54,6,vdx);
        A_PUT(Part54,7,vdy);
        A_PUT(Part54,8,vdz);	
    }
    
    /*计算零件6-1相关参数 calculate parameter of part6-1*/
    if(Pad_Switch == "on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;
        distance = Ladder_Size_W/2 + flatbar_thick + 0.5*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   	
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = zdx;
        vdy = zdy;
        vdz = zdz;
        A_PUT(Part61,0,lox);
        A_PUT(Part61,1,loy);
        A_PUT(Part61,2,loz); 
        A_PUT(Part61,3,udx);
        A_PUT(Part61,4,udy);
        A_PUT(Part61,5,udz);  
        A_PUT(Part61,6,vdx);
        A_PUT(Part61,7,vdy);
        A_PUT(Part61,8,vdz);	
    }  

    /*计算零件6-2相关参数 calculate parameter of part6-2*/
    if(Pad_Switch == "on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;
        distance = -(Ladder_Size_W/2 + flatbar_thick + 0.5*flatbar_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = -Ladder_Size_h1 + 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   	
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = zdx;
        vdy = zdy;
        vdz = zdz;
        A_PUT(Part62,0,lox);
        A_PUT(Part62,1,loy);
        A_PUT(Part62,2,loz); 
        A_PUT(Part62,3,udx);
        A_PUT(Part62,4,udy);
        A_PUT(Part62,5,udz);  
        A_PUT(Part62,6,vdx);
        A_PUT(Part62,7,vdy);
        A_PUT(Part62,8,vdz);
    }  

    /*计算零件6-3相关参数 calculate parameter of part6-3*/
    if(Pad_Switch == "on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;
        distance = Ladder_Size_W/2 + flatbar_thick + 0.5*flatbar_thick;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = Ladder_Size_d2 - Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   	
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = zdx;
        vdy = zdy;
        vdz = zdz;
        A_PUT(Part63,0,lox);
        A_PUT(Part63,1,loy);
        A_PUT(Part63,2,loz); 
        A_PUT(Part63,3,udx);
        A_PUT(Part63,4,udy);
        A_PUT(Part63,5,udz);  
        A_PUT(Part63,6,vdx);
        A_PUT(Part63,7,vdy);
        A_PUT(Part63,8,vdz);
    }  
    
    /*计算零件6-4相关参数 calculate parameter of part6-4*/
    if(Pad_Switch == "on"){
        x = Ladder_X0;
        y = Ladder_Y0;
        z = Ladder_Z0;
        distance = -(Ladder_Size_W/2 + flatbar_thick + 0.5*flatbar_thick);
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz,distance);
        distance = Ladder_Size_d2 - Ladder_Size_d1;
        Point_3D_Move_With_DirAndDis(x,y,z,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,distance);
        distance = -Ladder_Size_h1 + Ladder_Size_L - 0.5*flatbar_width;
        Point_3D_Move_With_DirAndDis(x,y,z,zdx,zdy,zdz,distance);   	
        lox = x;
        loy = y;
        loz = z;
        udx = Ladder_X_Dx;
        udy = Ladder_X_Dy;
        udz = Ladder_X_Dz;
        vdx = zdx;
        vdy = zdy;
        vdz = zdz;
        A_PUT(Part64,0,lox);
        A_PUT(Part64,1,loy);
        A_PUT(Part64,2,loz); 
        A_PUT(Part64,3,udx);
        A_PUT(Part64,4,udy);
        A_PUT(Part64,5,udz);  
        A_PUT(Part64,6,vdx);
        A_PUT(Part64,7,vdy);
        A_PUT(Part64,8,vdz);
    }  

    return(0);
}

/*扁钢双45度切角*/
calculate_flatbar_double_cut_para(flatbar_width,size_a)
{
    /* cut_para = "0 0 0 -22.5 0.0 -45.0;0 0 0 -22.5 0.0 45.0;"; */
    offset = 0.5*flatbar_width-size_a;
    offset_str = rtrim_number(FTOASCII(-offset));
    cut_para = "0 0 0 "+offset_str+" 0.0 -45.0;0 0 0 "+offset_str+" 0.0 45.0;";
    return(cut_para);
}

create_ladder()
{                            
    /* 获取零件参数 */
    flatbar_width = 1.0*DM_PARTID_DATA(Ladder_Part1_Pid, "D31");
    flatbar_thick = 1.0*DM_PARTID_DATA(Ladder_Part1_Pid, "D32");
    if(Pad_Switch == "on"){
        pad_plate_thick = 1.0*DM_PARTID_DATA(Ladder_Part6_Pid, "D31");
    }
    else{
        pad_plate_thick = 0.0;
    }
     
    /* 定义直梯零件集合 */   
    ladder = PM_INIT_SET();   
    /* 生成零件1-1 create part 1-1*/
    if(1){
        x1 =    A_GET(Part11,0);
        y1 =    A_GET(Part11,1);
        z1 =    A_GET(Part11,2);
        x2 =    A_GET(Part11,3);
        y2 =    A_GET(Part11,4);
        z2 =    A_GET(Part11,5);   
        x_dx =  A_GET(Part11,6);
        x_dy =  A_GET(Part11,7);
        x_dz =  A_GET(Part11,8);   
        end1x = A_GET(Part11,9);
        end1y = A_GET(Part11,10);
        end1z = A_GET(Part11,11);	
        end2x = A_GET(Part11,12);
        end2y = A_GET(Part11,13);
        end2z = A_GET(Part11,14);	
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part1_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "1-1");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    } 

    /* 生成零件1-2 create part 1-2*/
    if(1){
        x1 =    A_GET(Part12,0);
        y1 =    A_GET(Part12,1);
        z1 =    A_GET(Part12,2);
        x2 =    A_GET(Part12,3);
        y2 =    A_GET(Part12,4);
        z2 =    A_GET(Part12,5);   
        x_dx =  A_GET(Part12,6);
        x_dy =  A_GET(Part12,7);
        x_dz =  A_GET(Part12,8);   
        end1x = A_GET(Part12,9);
        end1y = A_GET(Part12,10);
        end1z = A_GET(Part12,11);	
        end2x = A_GET(Part12,12);
        end2y = A_GET(Part12,13);
        end2z = A_GET(Part12,14);	
        
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part1_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "1-2");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder);
    }   
    
    /* 生成零件1-3 create part 1-3*/
    if(1){
        x1 =    A_GET(Part13,0);
        y1 =    A_GET(Part13,1);
        z1 =    A_GET(Part13,2);
        x2 =    A_GET(Part13,3);
        y2 =    A_GET(Part13,4);
        z2 =    A_GET(Part13,5);   
        x_dx =  A_GET(Part13,6);
        x_dy =  A_GET(Part13,7);
        x_dz =  A_GET(Part13,8);   
        end1x = A_GET(Part13,9);
        end1y = A_GET(Part13,10);
        end1z = A_GET(Part13,11);	
        end2x = A_GET(Part13,12);
        end2y = A_GET(Part13,13);
        end2z = A_GET(Part13,14);	
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part1_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "1-3");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
        
        /* 旋转支撑腿 */
        angle = 90-Ladder_Size_ad;
        if(Abs(angle)>0.01){
            px = x1; py = y1; pz = z1;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,0.5*flatbar_width);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }
    } 

    /* 生成零件1-4 create part 1-4*/
    if(1){       
        x1 =    A_GET(Part14,0);
        y1 =    A_GET(Part14,1);
        z1 =    A_GET(Part14,2);
        x2 =    A_GET(Part14,3);
        y2 =    A_GET(Part14,4);
        z2 =    A_GET(Part14,5);   
        x_dx =  A_GET(Part14,6);
        x_dy =  A_GET(Part14,7);
        x_dz =  A_GET(Part14,8);   
        end1x = A_GET(Part14,9);
        end1y = A_GET(Part14,10);
        end1z = A_GET(Part14,11);	
        end2x = A_GET(Part14,12);
        end2y = A_GET(Part14,13);
        end2z = A_GET(Part14,14);	
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part1_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "1-4");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
        
        /* 旋转支撑腿 */
        angle = 90-Ladder_Size_ad;
        if(Abs(angle)>0.01){
            px = x1; py = y1; pz = z1;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,0.5*flatbar_width);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }
    }	
	
    /* 生成零件1-5 create part 1-5*/
    if(1){      
        x1 =    A_GET(Part15,0);
        y1 =    A_GET(Part15,1);
        z1 =    A_GET(Part15,2);
        x2 =    A_GET(Part15,3);
        y2 =    A_GET(Part15,4);
        z2 =    A_GET(Part15,5);   
        x_dx =  A_GET(Part15,6);
        x_dy =  A_GET(Part15,7);
        x_dz =  A_GET(Part15,8);   
        end1x = A_GET(Part15,9);
        end1y = A_GET(Part15,10);
        end1z = A_GET(Part15,11);	
        end2x = A_GET(Part15,12);
        end2y = A_GET(Part15,13);
        end2z = A_GET(Part15,14);	
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part1_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "1-5");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
        
        /* 旋转支撑腿 */
        angle = Ladder_Size_bd-90;
        if(Abs(angle)>0.01){
            px = x1; py = y1; pz = z1;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,0.5*flatbar_width);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }
    }

    /* 生成零件1-6 create part 1-6*/
    if(1){       
        x1 =    A_GET(Part16,0);
        y1 =    A_GET(Part16,1);
        z1 =    A_GET(Part16,2);
        x2 =    A_GET(Part16,3);
        y2 =    A_GET(Part16,4);
        z2 =    A_GET(Part16,5);   
        x_dx =  A_GET(Part16,6);
        x_dy =  A_GET(Part16,7);
        x_dz =  A_GET(Part16,8);   
        end1x = A_GET(Part16,9);
        end1y = A_GET(Part16,10);
        end1z = A_GET(Part16,11);	
        end2x = A_GET(Part16,12);
        end2y = A_GET(Part16,13);
        end2z = A_GET(Part16,14);
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part1_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "1-6");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
        
        /* 旋转支撑腿 */
        angle = Ladder_Size_bd-90;
        if(Abs(angle)>0.01){
            px = x1; py = y1; pz = z1;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,0.5*flatbar_width);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }
    }	
    
    /* 生成零件2-1 create part 2-1*/
    if(1){      
        x1 =    A_GET(Part21,0);
        y1 =    A_GET(Part21,1);
        z1 =    A_GET(Part21,2);
        x2 =    A_GET(Part21,3);
        y2 =    A_GET(Part21,4);
        z2 =    A_GET(Part21,5);   
        x_dx =  A_GET(Part21,6);
        x_dy =  A_GET(Part21,7);
        x_dz =  A_GET(Part21,8);   
        end1x = A_GET(Part21,9);
        end1y = A_GET(Part21,10);
        end1z = A_GET(Part21,11);	
        end2x = A_GET(Part21,12);
        end2y = A_GET(Part21,13);
        end2z = A_GET(Part21,14);
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part2_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "2-1");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
        
        /* 复制踏步 */
        zdx = 0;zdy = 0;zdz = 0;
        VEC_CROSS_PRODUCT(Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz, zdx,zdy,zdz);
        VEC_UNITV(zdx,zdy,zdz);
        
        part_index = 2;
        distance = Ladder_Size_h;
        copy_count = calculate_ladder_step_count();
        for(c=0;c<copy_count;c=c+1){
            copy_part_handle = copy_move_step(zdx,zdy,zdz, distance, part_handle);
            distance = distance + Ladder_Size_h;
            Set_Attribute_Value(copy_part_handle, PartNumber,  "2-"+ITOASCII(part_index));
            PM_ADD_OBJECT_TO_SET(copy_part_handle, ladder); 
            part_index = part_index + 1;
        }
    } 

    /* 生成零件2-2 create part 2-2*/
    if(1){      
        x1 =    A_GET(Part22,0);
        y1 =    A_GET(Part22,1);
        z1 =    A_GET(Part22,2);
        x2 =    A_GET(Part22,3);
        y2 =    A_GET(Part22,4);
        z2 =    A_GET(Part22,5);   
        x_dx =  A_GET(Part22,6);
        x_dy =  A_GET(Part22,7);
        x_dz =  A_GET(Part22,8);   
        end1x = A_GET(Part22,9);
        end1y = A_GET(Part22,10);
        end1z = A_GET(Part22,11);	
        end2x = A_GET(Part22,12);
        end2y = A_GET(Part22,13);
        end2z = A_GET(Part22,14);
        
        lox = 0;loy = 0;loz = 0;
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Beam(Ladder_Part2_Pid,Info_System_Id,x1,y1,z1,x2,y2,z2,x_dx,x_dy,x_dz,
                                  end1x,end1y,end1z,end2x,end2y,end2z,tmat_h);                       
        /* Set_Attribute_Value(part_handle, PartNumber,  "2-2");   */
        Set_Attribute_Value(copy_part_handle, PartNumber,  "2-"+ITOASCII(copy_count+2));        
        PM_ADD_OBJECT_TO_SET(part_handle, ladder);
    } 
	
    /* 生成零件3-1 create part 3-1*/
    if(Bolt_Switch=="on"){
        x =     A_GET(Part31,0);
        y =     A_GET(Part31,1);
        z =     A_GET(Part31,2);
        x_dx =  A_GET(Part31,3);
        x_dy =  A_GET(Part31,4);
        x_dz =  A_GET(Part31,5);   
        y_dx =  A_GET(Part31,6);
        y_dy =  A_GET(Part31,7);
        y_dz =  A_GET(Part31,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part3_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "3-1");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    } 
    
    /* 生成零件3-2 create part 3-2*/
    if(Bolt_Switch=="on"){
        x =     A_GET(Part32,0);
        y =     A_GET(Part32,1);
        z =     A_GET(Part32,2);
        x_dx =  A_GET(Part32,3);
        x_dy =  A_GET(Part32,4);
        x_dz =  A_GET(Part32,5);   
        y_dx =  A_GET(Part32,6);
        y_dy =  A_GET(Part32,7);
        y_dz =  A_GET(Part32,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part3_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "3-2");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    } 
    
    /* 生成零件3-3 create part 3-3*/
    if(Bolt_Switch=="on"){
        x =     A_GET(Part33,0);
        y =     A_GET(Part33,1);
        z =     A_GET(Part33,2);
        x_dx =  A_GET(Part33,3);
        x_dy =  A_GET(Part33,4);
        x_dz =  A_GET(Part33,5);   
        y_dx =  A_GET(Part33,6);
        y_dy =  A_GET(Part33,7);
        y_dz =  A_GET(Part33,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part3_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "3-3");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    } 
    
    /* 生成零件3-4 create part 3-4*/
    if(Bolt_Switch=="on"){
        x =     A_GET(Part34,0);
        y =     A_GET(Part34,1);
        z =     A_GET(Part34,2);
        x_dx =  A_GET(Part34,3);
        x_dy =  A_GET(Part34,4);
        x_dz =  A_GET(Part34,5);   
        y_dx =  A_GET(Part34,6);
        y_dy =  A_GET(Part34,7);
        y_dz =  A_GET(Part34,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part3_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "3-4");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }     
    
    /* 生成零件4-1 create part 4-1*/
    if(Nut_Switch=="on"){
        x =     A_GET(Part41,0);
        y =     A_GET(Part41,1);
        z =     A_GET(Part41,2);
        x_dx =  A_GET(Part41,3);
        x_dy =  A_GET(Part41,4);
        x_dz =  A_GET(Part41,5);   
        y_dx =  A_GET(Part41,6);
        y_dy =  A_GET(Part41,7);
        y_dz =  A_GET(Part41,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part4_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "4-1");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }  
    
    /* 生成零件4-2 create part 4-2*/
    if(Nut_Switch=="on"){
        x =     A_GET(Part42,0);
        y =     A_GET(Part42,1);
        z =     A_GET(Part42,2);
        x_dx =  A_GET(Part42,3);
        x_dy =  A_GET(Part42,4);
        x_dz =  A_GET(Part42,5);   
        y_dx =  A_GET(Part42,6);
        y_dy =  A_GET(Part42,7);
        y_dz =  A_GET(Part42,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part4_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "4-2");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }     
    
    /* 生成零件4-3 create part 4-3*/
    if(Nut_Switch=="on"){
        x =     A_GET(Part43,0);
        y =     A_GET(Part43,1);
        z =     A_GET(Part43,2);
        x_dx =  A_GET(Part43,3);
        x_dy =  A_GET(Part43,4);
        x_dz =  A_GET(Part43,5);   
        y_dx =  A_GET(Part43,6);
        y_dy =  A_GET(Part43,7);
        y_dz =  A_GET(Part43,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part4_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "4-3");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }     
    
    /* 生成零件4-4 create part 4-4*/
    if(Nut_Switch=="on"){
        x =     A_GET(Part44,0);
        y =     A_GET(Part44,1);
        z =     A_GET(Part44,2);
        x_dx =  A_GET(Part44,3);
        x_dy =  A_GET(Part44,4);
        x_dz =  A_GET(Part44,5);   
        y_dx =  A_GET(Part44,6);
        y_dy =  A_GET(Part44,7);
        y_dz =  A_GET(Part44,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part4_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "4-4");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }    
    
    /* 生成零件5-1 create part 5-1*/
    if(Washer_Switch=="on"){
        x =     A_GET(Part51,0);
        y =     A_GET(Part51,1);
        z =     A_GET(Part51,2);
        x_dx =  A_GET(Part51,3);
        x_dy =  A_GET(Part51,4);
        x_dz =  A_GET(Part51,5);   
        y_dx =  A_GET(Part51,6);
        y_dy =  A_GET(Part51,7);
        y_dz =  A_GET(Part51,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part5_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "5-1");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }    
    
    /* 生成零件5-2 create part 5-2*/
    if(Washer_Switch=="on"){
        x =     A_GET(Part52,0);
        y =     A_GET(Part52,1);
        z =     A_GET(Part52,2);
        x_dx =  A_GET(Part52,3);
        x_dy =  A_GET(Part52,4);
        x_dz =  A_GET(Part52,5);   
        y_dx =  A_GET(Part52,6);
        y_dy =  A_GET(Part52,7);
        y_dz =  A_GET(Part52,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part5_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "5-2");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }    
    
    /* 生成零件5-3 create part 5-3*/
    if(Washer_Switch=="on"){
        x =     A_GET(Part53,0);
        y =     A_GET(Part53,1);
        z =     A_GET(Part53,2);
        x_dx =  A_GET(Part53,3);
        x_dy =  A_GET(Part53,4);
        x_dz =  A_GET(Part53,5);   
        y_dx =  A_GET(Part53,6);
        y_dy =  A_GET(Part53,7);
        y_dz =  A_GET(Part53,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part5_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "5-3");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }    
    
    /* 生成零件5-4 create part 5-4*/
    if(Washer_Switch=="on"){
        x =     A_GET(Part54,0);
        y =     A_GET(Part54,1);
        z =     A_GET(Part54,2);
        x_dx =  A_GET(Part54,3);
        x_dy =  A_GET(Part54,4);
        x_dz =  A_GET(Part54,5);   
        y_dx =  A_GET(Part54,6);
        y_dy =  A_GET(Part54,7);
        y_dz =  A_GET(Part54,8);   
	
        lox = 0;loy = 0;loz = 0;	
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,1,0,0,0,1,0);   
        part_handle = Create_Standcomp(Ladder_Part5_Pid,Info_System_Id,x,y,z,
                                       x_dx,x_dy,x_dz,y_dx,y_dy,y_dz,tmat_h);                       
        Set_Attribute_Value(part_handle, PartNumber,  "5-4");   
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 
    }    

    /* 生成零件6-1 create part 6-1*/
    if(Pad_Switch == "on"){
        size_a = Ladder_Size_a; 
        size_b = Ladder_Size_b; 
        size_r = Ladder_Size_r;
        hole_list = alloc_2darray(0, 0);  
        /*calculate_hole_list(hole_list,Ladder_Size_W);*/
        curve = create_rect_curve_with_radius(size_a,size_b,size_r);
        
        lox = A_GET(Part61,0);
        loy = A_GET(Part61,1);
        loz = A_GET(Part61,2);	
        udx = A_GET(Part61,3);
        udy = A_GET(Part61,4);
        udz = A_GET(Part61,5);
        vdx = A_GET(Part61,6);
        vdy = A_GET(Part61,7);
        vdz = A_GET(Part61,8); 

        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,udx,udy,udz,vdx,vdy,vdz);	    	 
        part_handle = Create_Plate(Ladder_Part6_Pid, Info_System_Id, curve, tmat_h, hole_list);         
        if(ISINT(part_handle)){
            free_2darray(hole_list);
            st = PM_UM_CLOSE_CHANGE();
            return(-1);
        }   
                
        Set_Attribute_Value(part_handle, PartNumber,  "6-1");	
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 		  
        free_2darray(hole_list);  

        /* 旋转垫板 */
        angle = 90-Ladder_Size_ad;
        if(Abs(angle)>0.01){
            px = lox; py = loy; pz = loz;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,-Ladder_Size_d1);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }
    } 

    /* 生成零件6-2 create part 6-2*/
    if(Pad_Switch == "on"){
        size_a = Ladder_Size_a; 
        size_b = Ladder_Size_b; 
        size_r = Ladder_Size_r;
        hole_list = alloc_2darray(0, 0);  
        /*calculate_hole_list(hole_list,Ladder_Size_W);*/
        curve = create_rect_curve_with_radius(size_a,size_b,size_r);
        
        lox = A_GET(Part62,0);
        loy = A_GET(Part62,1);
        loz = A_GET(Part62,2);	
        udx = A_GET(Part62,3);
        udy = A_GET(Part62,4);
        udz = A_GET(Part62,5);
        vdx = A_GET(Part62,6);
        vdy = A_GET(Part62,7);
        vdz = A_GET(Part62,8); 
        
        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,udx,udy,udz,vdx,vdy,vdz);	    	 
        part_handle = Create_Plate(Ladder_Part6_Pid, Info_System_Id, curve, tmat_h, hole_list);         
        if(ISINT(part_handle)){
            free_2darray(hole_list);
            st = PM_UM_CLOSE_CHANGE();
            return(-1);
        }
        
        Set_Attribute_Value(part_handle, PartNumber,  "6-2");	
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 		  
        free_2darray(hole_list);  
        
        /* 旋转垫板 */
        angle = 90-Ladder_Size_ad;
        if(Abs(angle)>0.01){
            px = lox; py = loy; pz = loz;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,-Ladder_Size_d1);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }
    } 
    
    /* 生成零件6-3 create part 6-3*/
    if(Pad_Switch == "on"){
        size_a = Ladder_Size_a; 
        size_b = Ladder_Size_b; 
        size_r = Ladder_Size_r;
        hole_list = alloc_2darray(0, 0);  
        /*calculate_hole_list(hole_list,Ladder_Size_W);*/
        curve = create_rect_curve_with_radius(size_a,size_b,size_r);
        
        lox = A_GET(Part63,0);
        loy = A_GET(Part63,1);
        loz = A_GET(Part63,2);	
        udx = A_GET(Part63,3);
        udy = A_GET(Part63,4);
        udz = A_GET(Part63,5);
        vdx = A_GET(Part63,6);
        vdy = A_GET(Part63,7);
        vdz = A_GET(Part63,8); 

        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,udx,udy,udz,vdx,vdy,vdz);	    	 
        part_handle = Create_Plate(Ladder_Part6_Pid, Info_System_Id, curve, tmat_h, hole_list);         
        if(ISINT(part_handle)){
            free_2darray(hole_list);
            st = PM_UM_CLOSE_CHANGE();
            return(-1);
        }   
                
        Set_Attribute_Value(part_handle, PartNumber,  "6-3");	
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 		  
        free_2darray(hole_list); 

        /* 旋转垫板 */
        angle = Ladder_Size_bd-90;
        if(Abs(angle)>0.01){
            px = lox; py = loy; pz = loz;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,-Ladder_Size_d2);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }        
    } 

    /* 生成零件6-4 create part 6-4*/
    if(Pad_Switch == "on"){
        size_a = Ladder_Size_a; 
        size_b = Ladder_Size_b; 
        size_r = Ladder_Size_r;
        hole_list = alloc_2darray(0, 0);  
        /*calculate_hole_list(hole_list,Ladder_Size_W);*/
        curve = create_rect_curve_with_radius(size_a,size_b,size_r);
        
        lox = A_GET(Part64,0);
        loy = A_GET(Part64,1);
        loz = A_GET(Part64,2);	
        udx = A_GET(Part64,3);
        udy = A_GET(Part64,4);
        udz = A_GET(Part64,5);
        vdx = A_GET(Part64,6);
        vdy = A_GET(Part64,7);
        vdz = A_GET(Part64,8); 

        tmat_h = PM_CREATE_TMAT(1,lox,loy,loz,udx,udy,udz,vdx,vdy,vdz);	    	 
        part_handle = Create_Plate(Ladder_Part6_Pid, Info_System_Id, curve, tmat_h, hole_list);         
        if(ISINT(part_handle)){
            free_2darray(hole_list);
            st = PM_UM_CLOSE_CHANGE();
            return(-1);
        }   
        
        Set_Attribute_Value(part_handle, PartNumber,  "6-4");	
        PM_ADD_OBJECT_TO_SET(part_handle, ladder); 		  
        free_2darray(hole_list); 
        
        /* 旋转垫板 */
        angle = Ladder_Size_bd-90;
        if(Abs(angle)>0.01){
            px = lox; py = loy; pz = loz;
            Point_3D_Move_With_DirAndDis(px,py,pz,Ladder_Y_Dx,Ladder_Y_Dy,Ladder_Y_Dz,-Ladder_Size_d2);
            rotate_part(px,py,pz, Ladder_X_Dx,Ladder_X_Dy,Ladder_X_Dz, angle, part_handle);
        }        
    } 
    
    PM_ADD_SET_TO_GROUP(ladder, Ladder_Handle);
    set_ladder_para(Ladder_Handle);
    save_model_size();
    PM_FREE_SET(ladder);   
	return(0);
}

calculate_hole_list(hole_list,hole_dia)
{
	hole1_size = "circle1 = CURVE(" + STRINGTERM(FTOASCII(hole_dia),".") + "\/ 2,0,ARC,0,0,360)\;";
	hole1_pos  = ",circle1,0,0";		
	
	/* 将开孔信息存入数组 */
	put_2darray(hole_list,0,0,hole1_size);
	put_2darray(hole_list,0,1,hole1_pos);	
	return(0);  
}

set_ladder_para(group_h)
{
    Set_Attribute_Value(group_h, PlanningUnit,  Info_Planning_Unit);
    Set_Attribute_Value(group_h, LadderDes,  Info_Ladder_Desc);
    Set_Attribute_Value(group_h, LadderType, Info_Ladder_Type);
    
    W_SET_NUMERIC_VALUE(Ladder_Para_L,  Ladder_Size_L);
    W_SET_NUMERIC_VALUE(Ladder_Para_W,  Ladder_Size_W);
    W_SET_NUMERIC_VALUE(Ladder_Para_h,  Ladder_Size_h);
    W_SET_NUMERIC_VALUE(Ladder_Para_h1, Ladder_Size_h1); 
    W_SET_NUMERIC_VALUE(Ladder_Para_h2, Ladder_Size_h2);   
    W_SET_NUMERIC_VALUE(Ladder_Para_d1, Ladder_Size_d1);   
    W_SET_NUMERIC_VALUE(Ladder_Para_d2, Ladder_Size_d2);   
    W_SET_NUMERIC_VALUE(Ladder_Para_a,  Ladder_Size_a);   
    W_SET_NUMERIC_VALUE(Ladder_Para_b,  Ladder_Size_b); 
    W_SET_NUMERIC_VALUE(Ladder_Para_r,  Ladder_Size_r); 
    return(0);
}

quit_handler(item, event_type, button_value)
{ 
    A_FREE(Part11);
    A_FREE(Part12);
    A_FREE(Part13);
    A_FREE(Part14);
    A_FREE(Part15);
    A_FREE(Part16);
    A_FREE(Part21);
    A_FREE(Part22);
    A_FREE(Part31);
    A_FREE(Part32);
    A_FREE(Part33);
    A_FREE(Part34);
    A_FREE(Part41);
    A_FREE(Part42);
    A_FREE(Part43);
    A_FREE(Part44);
    A_FREE(Part51);
    A_FREE(Part52);
    A_FREE(Part53);
    A_FREE(Part54);
    A_FREE(Part61);
    A_FREE(Part62);
    A_FREE(Part63);
    A_FREE(Part64);
    
	U_MESSAGE("退出直梯参数化建模窗口");
	return(99);
}

/*
**创建用于输入及编辑直梯参数的面板
*/
create_parameter_panel(mainform)
{
	Parameters = W_ADD_WINDOW(mainform, W_PANEL, "Parameters");
	W_REALIZE_WINDOW(Parameters,  W_FRAME_X, 465,
	                              W_FRAME_Y, 340,
							      W_FRAME_WIDTH, 100,
							      W_FRAME_HEIGHT, 130);

	title = W_ADD_PANELITEM(Parameters, W_PANEL_MESSAGE, "title");
	W_REALIZE_PANELITEM(title, W_PANEL_ROW,	0,
		                       W_PANEL_COL,	0,
		                       W_PANEL_LABEL,	"直梯尺寸");

    seperate_line = W_ADD_PANELITEM(Parameters, W_PANEL_MESSAGE, "seperate_line");
	W_REALIZE_PANELITEM(seperate_line,  W_PANEL_ROW, 0,
	                                    W_PANEL_COL, 7,
		                                W_PANEL_LABEL,	"",
		                                W_PANEL_SEPARATOR, 1);

	Ladder_Para_L = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_L");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_L, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_L, W_PANEL_ROW, 1, 
	                                   W_PANEL_COL, 1,
							           W_PANEL_LABEL, " L: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);      							               
	W_SET_PANELITEM_HANDLER(Ladder_Para_L, "ladder_para_handler"); 
	
	Ladder_Para_W = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_W");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_W, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_W, W_PANEL_ROW, 1, 
	                                   W_PANEL_COL, 12,
							           W_PANEL_LABEL, " W: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);
	W_SET_PANELITEM_HANDLER(Ladder_Para_W, "ladder_para_handler");

	Ladder_Para_h1 = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_h1");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_h1, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_h1, W_PANEL_ROW, 2, 
                                        W_PANEL_COL, 1,
                                        W_PANEL_LABEL, "h1: ",
                                        W_PANEL_LENGTH, 6,
                                        W_PANEL_CALLBACK, 1);          							               
	W_SET_PANELITEM_HANDLER(Ladder_Para_h1, "ladder_para_handler");

	Ladder_Para_h2 = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_h2");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_h2, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_h2, W_PANEL_ROW, 2, 
                                        W_PANEL_COL, 12,
                                        W_PANEL_LABEL, "h2: ",
                                        W_PANEL_LENGTH, 6,
                                        W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_h2, "ladder_para_handler");	

	Ladder_Para_d1 = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_d1");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_d1, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_d1, W_PANEL_ROW, 3, 
                                        W_PANEL_COL, 1,
                                        W_PANEL_LABEL, "d1: ",
                                        W_PANEL_LENGTH, 6,
                                        W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_d1, "ladder_para_handler");	

	Ladder_Para_d2 = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_d2");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_d2, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_d2, W_PANEL_ROW, 3, 
                                        W_PANEL_COL, 12,
                                        W_PANEL_LABEL, "d2: ",
                                        W_PANEL_LENGTH, 6,
                                        W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_d2, "ladder_para_handler");

	Ladder_Para_h = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_h");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_h, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_h, W_PANEL_ROW, 4, 
	                                   W_PANEL_COL, 1,
							           W_PANEL_LABEL, " h: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_h, "ladder_para_handler");  

	Ladder_Para_a = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_a");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_a, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_a, W_PANEL_ROW, 4, 
	                                   W_PANEL_COL, 12,
							           W_PANEL_LABEL, " a: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_a, "ladder_para_handler");  

	Ladder_Para_b = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_b");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_b, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_b, W_PANEL_ROW, 5, 
	                                   W_PANEL_COL, 1,
							           W_PANEL_LABEL, " b: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_b, "ladder_para_handler");  
    
	Ladder_Para_r = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_r");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_r, W_NUMERIC_FLOAT, 1, 10000, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_r, W_PANEL_ROW, 5, 
	                                   W_PANEL_COL, 12,
							           W_PANEL_LABEL, " r: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_r, "ladder_para_handler");  

	Ladder_Para_ad = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_ad");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_ad, W_NUMERIC_FLOAT, 1, 360, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_ad, W_PANEL_ROW, 6, 
	                                    W_PANEL_COL, 1,
							            W_PANEL_LABEL, "a°: ",
							            W_PANEL_LENGTH, 6,
							            W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_ad, "ladder_para_handler");  

	Ladder_Para_bd = W_ADD_PANELITEM(Parameters, W_PANEL_FILL, "Ladder_Para_bd");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Para_bd, W_NUMERIC_FLOAT, 1, 360, "%.0f");
	W_REALIZE_PANELITEM(Ladder_Para_bd, W_PANEL_ROW, 6, 
	                                   W_PANEL_COL, 12,
							           W_PANEL_LABEL, "b°: ",
							           W_PANEL_LENGTH, 6,
							           W_PANEL_CALLBACK, 1);					               
	W_SET_PANELITEM_HANDLER(Ladder_Para_bd, "ladder_para_handler");  
    
	return(Parameters);
}

/*
**处理直梯参数发生更改的事件
*/
ladder_para_handler(item, event_type, dummy)
{  
    /* 处理输入新数值后 */
    if (event_type == W_EVENT_ITEM_LEFT){
        /* 检查参数是否正确 */
        if (item == Ladder_Para_L){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_L", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_L = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_L", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:L");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }           
                st = PM_UM_CLOSE_CHANGE();           
            }                 
        }
        else if (item == Ladder_Para_W){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_W", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_W = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_W", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:W");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_h){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_h = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:h");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_h1){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h1", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_h1 = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h1", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:h1");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_h2){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h2", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_h2 = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h2", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:h2");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_d1){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d1", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_d1 = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d1", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:d1");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_d2){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d2", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_d2 = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d2", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:d2");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_a){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_a", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_a = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_a", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:a");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_b){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_b", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_b = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_b", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:b");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_r){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_r", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_r = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_r", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:r");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_ad){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_ad", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_ad = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_ad", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:ad");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        else if (item == Ladder_Para_bd){
            st = 0;
            value = W_GET_NUMERIC_VALUE(item, st);
            if (st != 0){
                orgin = 0;
                st1 = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_bd", orgin);
                if(st1 == 0){
                    W_SET_NUMERIC_VALUE(item, orgin);
                    value = orgin;
                }
                else{
                    W_SET_NUMERIC_VALUE(item, 0);
                    return(-1);
                }
            }

            Ladder_Size_bd = value;
            st = SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_bd", value);

            if(Modify_flag){
                /* 定义UNDO缓存 define cache for undo */
                st = PM_UM_OPEN_CHANGE("修改直梯参数:bd");
                calculate_ladder_para();
                delete_ladder_members();
                res = create_ladder(); 
                if (res == -1){
                    PM_UM_CLOSE_CHANGE();
                    PM_UM_UNDO_LAST_CHANGE();
                    return(0);
                }  
                st = PM_UM_CLOSE_CHANGE();
            }
        }
        
    }
    return(0); 
}

/*
**创建用于输入及编辑直梯位置的面板
*/
create_position_panel(mainform)
{
	Position = W_ADD_WINDOW(mainform, W_PANEL, "Position");
	W_REALIZE_WINDOW(Position,  W_FRAME_X, 465,
	                            W_FRAME_Y, 530,
							    W_FRAME_WIDTH, 100,
							    W_FRAME_HEIGHT, 180);

	title = W_ADD_PANELITEM(Position, W_PANEL_MESSAGE, "title");
	W_REALIZE_PANELITEM(title, W_PANEL_ROW,	0,
		                       W_PANEL_COL,	0,
		                       W_PANEL_LABEL,	"直梯位置");

    seperate_line = W_ADD_PANELITEM(Position, W_PANEL_MESSAGE, "seperate_line");
	W_REALIZE_PANELITEM(seperate_line,  W_PANEL_ROW, 0,
	                                    W_PANEL_COL, 7,
		                                W_PANEL_LABEL,	"",
		                                W_PANEL_SEPARATOR, 1);
   
	/* 直梯位置信息-绝对坐标 */
	Ladder_Position_X = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_X");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Position_X, W_NUMERIC_INT,
                                                  -1000000, 1000000);                                          	
	W_REALIZE_PANELITEM(Ladder_Position_X, W_PANEL_ROW, 1, 
	                                       W_PANEL_COL, 0,
							               W_PANEL_LABEL, "X: ",
							               W_PANEL_LENGTH, 7,
							               W_PANEL_VALUE, "0",
							               W_PANEL_CALLBACK, 1);	
	W_SET_NUMERIC_VALUE(Ladder_Position_X, 10000);						                     	
	W_SET_PANELITEM_HANDLER(Ladder_Position_X, "ladder_position_handler"); 

	Ladder_Position_Y = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Y");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Position_Y, W_NUMERIC_INT,
                                                  -1000000, 1000000);	
	W_REALIZE_PANELITEM(Ladder_Position_Y, W_PANEL_ROW, 2, 
	                                       W_PANEL_COL, 0,
							               W_PANEL_LABEL, "Y: ",
							               W_PANEL_LENGTH, 7,
							               W_PANEL_VALUE, "0",
							               W_PANEL_CALLBACK, 1);							                     
	W_SET_NUMERIC_VALUE(Ladder_Position_Y, 10000);							                     							                     
	W_SET_PANELITEM_HANDLER(Ladder_Position_Y, "ladder_position_handler");

	Ladder_Position_Z = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Z");
    W_CONFIG_NUMERIC_PANELITEM(Ladder_Position_Z, W_NUMERIC_INT,
                                                  -1000000, 1000000);	
	W_REALIZE_PANELITEM(Ladder_Position_Z, W_PANEL_ROW, 3, 
	                                       W_PANEL_COL, 0,
							               W_PANEL_LABEL, "Z: ",
							               W_PANEL_LENGTH, 7,
							               W_PANEL_VALUE, "0",
							               W_PANEL_CALLBACK, 1);							                     
	W_SET_NUMERIC_VALUE(Ladder_Position_Z, 10000);							                     							                     
	W_SET_PANELITEM_HANDLER(Ladder_Position_Z, "ladder_position_handler");	

	/* 直梯位置信息-参考面 */
	Ladder_Position_Xref = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Xref");
	W_REALIZE_PANELITEM(Ladder_Position_Xref,	W_PANEL_ROW, 			1, 
                                                W_PANEL_COL, 			11,
                                                W_PANEL_LABEL, 			"",
                                                W_PANEL_LENGTH, 		6,
                                                W_PANEL_VALUE, 			"",
                                                W_PANEL_SENSITIVITY,	0,
                                                W_PANEL_CALLBACK, 		1);							                     
	W_SET_PANELITEM_HANDLER(Ladder_Position_Xref, "ladder_position_handler"); 

	Ladder_Position_Yref = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Yref");	
	W_REALIZE_PANELITEM(Ladder_Position_Yref,	W_PANEL_ROW, 			2, 
                                                W_PANEL_COL, 			11,
                                                W_PANEL_LABEL, 			"",
                                                W_PANEL_LENGTH, 		6,
                                                W_PANEL_VALUE, 			"",
                                                W_PANEL_SENSITIVITY,	0,
                                                W_PANEL_CALLBACK, 		1);
	W_SET_PANELITEM_HANDLER(Ladder_Position_Yref, "ladder_position_handler");
    
	Ladder_Position_Zref = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Zref");	
	W_REALIZE_PANELITEM(Ladder_Position_Zref,	W_PANEL_ROW, 			3, 
                                                W_PANEL_COL, 			11,
                                                W_PANEL_LABEL, 			"",
                                                W_PANEL_LENGTH, 		6,
                                                W_PANEL_VALUE, 			"",
                                                W_PANEL_SENSITIVITY,	0,
                                                W_PANEL_CALLBACK, 		1);							                        
	W_SET_PANELITEM_HANDLER(Ladder_Position_Zref, "ladder_position_handler");	

	/* 直梯位置信息-偏移量 */	
	Ladder_Position_Xoff = W_ADD_PANELITEM(Position,	W_PANEL_FILL, "Ladder_Position_Xoff");
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Position_Xoff,	W_NUMERIC_INT,
                                                        -10000, 10000);	
	W_REALIZE_PANELITEM(Ladder_Position_Xoff,	W_PANEL_ROW, 			1, 
                                                W_PANEL_COL, 			18,
                                                W_PANEL_LABEL, 			"",
                                                W_PANEL_LENGTH, 		6,
                                                W_PANEL_VALUE, 			"",
                                                W_PANEL_SENSITIVITY,	0,
                                                W_PANEL_CALLBACK, 		1);							                     	
	W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, 0);	
	W_SET_PANELITEM_HANDLER(Ladder_Position_Xoff, "ladder_position_handler"); 

	Ladder_Position_Yoff = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Yoff");
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Position_Yoff,	W_NUMERIC_INT,
                                                        -10000, 10000);	
	W_REALIZE_PANELITEM(Ladder_Position_Yoff,	W_PANEL_ROW, 			2, 
                                                W_PANEL_COL, 			18,
                                                W_PANEL_LABEL, 			"",
                                                W_PANEL_LENGTH, 		6,
                                                W_PANEL_VALUE, 			"",
                                                W_PANEL_SENSITIVITY,	0,
                                                W_PANEL_CALLBACK, 		1);							                        
	W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, 0);							                        
	W_SET_PANELITEM_HANDLER(Ladder_Position_Yoff, "ladder_position_handler");

	Ladder_Position_Zoff = W_ADD_PANELITEM(Position, W_PANEL_FILL, "Ladder_Position_Zoff");
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Position_Zoff,	W_NUMERIC_INT,
                                                        -10000, 10000);
	W_REALIZE_PANELITEM(Ladder_Position_Zoff,	W_PANEL_ROW, 			3, 
                                                W_PANEL_COL, 			18,
                                                W_PANEL_LABEL, 			"",
                                                W_PANEL_LENGTH, 		6,
                                                W_PANEL_VALUE, 			"",
                                                W_PANEL_SENSITIVITY,	0,
                                                W_PANEL_CALLBACK, 		1);
	W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, 0);						                                        
	W_SET_PANELITEM_HANDLER(Ladder_Position_Zoff, "ladder_position_handler");	

	Pick_Ladder_Position = W_ADD_PANELITEM(Position, W_PANEL_BUTTON, "Pick_Ladder_Position");	
	W_REALIZE_PANELITEM(Pick_Ladder_Position,	W_PANEL_ROW, 			4, 
                                                W_PANEL_COL, 			0,
                                                W_PANEL_BUTTONIMAGE, 	"点选位置", 
                                                W_PANEL_WIDTH, 			24,
                                                W_PANEL_BUTTONVALUE, 	601,
                                                W_PANEL_CALLBACK, 		1,
                                                W_PANEL_LAYOUT,			W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(Pick_Ladder_Position, "pick_ladder_position_handler");
		         														
	return(Position);
}

/*
**用于处理直梯坐标的输入
*/
ladder_position_handler(item, event_type, dummy)
{     
	if (event_type == W_EVENT_ITEM_LEFT){     
		if (item == Ladder_Position_X | item == Ladder_Position_Y | item == Ladder_Position_Z){         
			st = 0;                  
			trans_abs_ref();
		}
		else if ( item == Ladder_Position_Xref | item == Ladder_Position_Yref | item == Ladder_Position_Zref){        
            x_ref = W_GET_PANELITEM_ARG(Ladder_Position_Xref, W_PANEL_VALUE);
            y_ref = W_GET_PANELITEM_ARG(Ladder_Position_Yref, W_PANEL_VALUE);
            z_ref = W_GET_PANELITEM_ARG(Ladder_Position_Zref, W_PANEL_VALUE);
            st = 0;
            x_off = W_GET_NUMERIC_VALUE(Ladder_Position_Xoff, st);
            y_off = W_GET_NUMERIC_VALUE(Ladder_Position_Yoff, st);
            z_off = W_GET_NUMERIC_VALUE(Ladder_Position_Zoff, st);                
            coord_ref_to_abs(x_ref,x_off,y_ref,y_off,x_ref,x_off);           
		}  
        if(Modify_flag){
            st = PM_UM_OPEN_CHANGE("修改直梯位置");
            calculate_ladder_para();
            delete_ladder_members();
            res = create_ladder(); 
            if (res == -1){
                PM_UM_CLOSE_CHANGE();
                PM_UM_UNDO_LAST_CHANGE();
                return(0);
            }  
            st = PM_UM_CLOSE_CHANGE();
        }           
	}
	return(0);
}

/*
**将相对坐标转换成绝对坐标
*/
coord_ref_to_abs(string x_ref,float x_off,string y_ref,float y_off,string Z_ref,float Z_off)
{
	st = 0;
	x0 = W_GET_NUMERIC_VALUE(Ladder_Position_X, st);
	y0 = W_GET_NUMERIC_VALUE(Ladder_Position_Y, st);
	z0 = W_GET_NUMERIC_VALUE(Ladder_Position_Z, st);
	return(0);
}

/*
**用于处理直梯在模型中捕捉直梯的位置
*/
pick_ladder_position_handler(item, event_type, button_value)
{
	/* 获取当前光标点坐标并显示到面板中 */
	x0 = 0;
	y0 = 0;
	z0 = 0;
   
	trace_handle = PM_NEW_TRACEP();  
	PM_GET_CURRENT_LOC(x0,y0,z0);  
	res = PM_GET_POINT("请选择直梯位置", trace_handle, x0, y0, z0); 
	if ( res < 0 ){
		return(-1);
	}
    
	W_SET_NUMERIC_VALUE(Ladder_Position_X, x0);
	W_SET_NUMERIC_VALUE(Ladder_Position_Y, y0);
	W_SET_NUMERIC_VALUE(Ladder_Position_Z, z0);
   
	trans_abs_ref();
    
	if(Modify_flag){
		st = PM_UM_OPEN_CHANGE("修改直梯位置");
		calculate_ladder_para();
		delete_ladder_members();
        res = create_ladder(); 
        if (res == -1){
            PM_UM_CLOSE_CHANGE();
            PM_UM_UNDO_LAST_CHANGE();
            return(0);
        }  
		st = PM_UM_CLOSE_CHANGE();
	}            
	return(0);
}

/*
**将绝对坐标转换成相对坐标
*/
trans_abs_ref()
{
	/* 将绝对坐标转换成相对坐标并显示到面板中 */   
	x_ref = "";
	y_ref = "";
	z_ref = "";
	x_offset = 0;
	y_offset = 0;
	z_offset = 0;
   
	x0 = 0;
	y0 = 0;
	z0 = 0;
   
	st = 0;
	x0 = W_GET_NUMERIC_VALUE(Ladder_Position_X,st);
	y0 = W_GET_NUMERIC_VALUE(Ladder_Position_Y,st);
	z0 = W_GET_NUMERIC_VALUE(Ladder_Position_Z,st);
   
	res = GetReferenceCoords( x0, y0, z0, x_ref, x_offset, y_ref, y_offset, z_ref, z_offset);
	if (res == 0){  
		W_SET_PANELITEM_ARGS(Ladder_Position_Xref, W_PANEL_VALUE, x_ref);
		W_SET_PANELITEM_ARGS(Ladder_Position_Yref, W_PANEL_VALUE, y_ref);
		W_SET_PANELITEM_ARGS(Ladder_Position_Zref, W_PANEL_VALUE, z_ref);
   
		W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, x_offset);
		W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, y_offset);
		W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, z_offset);     
	}  
	else if (res == -1){     
		W_SET_PANELITEM_ARGS(Ladder_Position_Xref, W_PANEL_VALUE, "Unset");
		W_SET_PANELITEM_ARGS(Ladder_Position_Yref, W_PANEL_VALUE, "Unset");
		W_SET_PANELITEM_ARGS(Ladder_Position_Zref, W_PANEL_VALUE, "Unset");
   
		W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, 0);
		W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, 0);
		W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, 0); 
		U_CONFIRM("参考坐标系定义不正确");           
	}    
}

/*
**创建用于旋转直梯的面板
*/
create_rotate_ladder_panel(mainform)
{
	Orientation = W_ADD_WINDOW(mainform, W_PANEL, "Orientation");	
	W_REALIZE_WINDOW(Orientation,	W_FRAME_X, 		680,
									W_FRAME_Y, 		340,
							        W_FRAME_WIDTH,	100,
							        W_FRAME_HEIGHT, 130);

	title = W_ADD_PANELITEM(Orientation, W_PANEL_MESSAGE, "title");
	W_REALIZE_PANELITEM(title,	W_PANEL_ROW,	0,
		                        W_PANEL_COL,	0,
		                        W_PANEL_LABEL,	"旋转直梯");

	seperate_line = W_ADD_PANELITEM(Orientation, W_PANEL_MESSAGE, "seperate_line");
	W_REALIZE_PANELITEM(seperate_line,	W_PANEL_ROW, 		0,
	                                    W_PANEL_COL, 		7,
		                                W_PANEL_LABEL,		"",
		                                W_PANEL_SEPARATOR,	1);         
	/* 直梯旋转轴 */   
	Ladder_Rotate_X = W_ADD_PANELITEM(Orientation, W_PANEL_FILL, "Ladder_Rotate_X");	
	W_REALIZE_PANELITEM(Ladder_Rotate_X,	W_PANEL_ROW,		1, 
                                            W_PANEL_COL,		0,
                                            W_PANEL_LABEL,		"X轴:",
                                            W_PANEL_LENGTH, 	0,
                                            W_PANEL_VALUE, 		"",
                                            W_PANEL_CALLBACK,	0);

	Ladder_Rotate_Y = W_ADD_PANELITEM(Orientation, W_PANEL_FILL, "Ladder_Rotate_Y");	
	W_REALIZE_PANELITEM(Ladder_Rotate_Y,	W_PANEL_ROW,		2, 
                                            W_PANEL_COL,		0,
                                            W_PANEL_LABEL,		"Y轴:",
                                            W_PANEL_LENGTH, 	0,
                                            W_PANEL_VALUE, 		"",
                                            W_PANEL_CALLBACK,	0);	
										
	Ladder_Rotate_Z = W_ADD_PANELITEM(Orientation, W_PANEL_FILL, "Ladder_Rotate_Z");	
	W_REALIZE_PANELITEM(Ladder_Rotate_Z,	W_PANEL_ROW,		3, 
                                            W_PANEL_COL,		0,
                                            W_PANEL_LABEL, 		"Z轴:",
                                            W_PANEL_LENGTH, 	0,
                                            W_PANEL_VALUE, 		"",
                                            W_PANEL_CALLBACK,	0);	
	/* 直梯旋转角度 */  
	Ladder_Rotate_Angle_X = W_ADD_PANELITEM(Orientation, W_PANEL_FILL, "Ladder_Rotate_Angle_X");
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Rotate_Angle_X, W_NUMERIC_FLOAT, 0.0, 180.0, "%.1f");	                                                  
	W_REALIZE_PANELITEM(Ladder_Rotate_Angle_X,	W_PANEL_ROW, 		1, 
												W_PANEL_COL, 		8,
							                    W_PANEL_LABEL, 		"",
							                    W_PANEL_LENGTH, 	6,
         							            W_PANEL_VALUE, 		"0.0",
         							            W_PANEL_CALLBACK, 	0);
	W_SET_NUMERIC_VALUE(Ladder_Rotate_Angle_X, 0.0);	

							               
	Ladder_Rotate_Angle_Y = W_ADD_PANELITEM(Orientation, W_PANEL_FILL, "Ladder_Rotate_Angle_Y");	
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Rotate_Angle_Y, W_NUMERIC_FLOAT, 0.0, 180.0, "%.1f");                                                                                                      
	W_REALIZE_PANELITEM(Ladder_Rotate_Angle_Y,	W_PANEL_ROW, 		2, 
												W_PANEL_COL, 		8,
												W_PANEL_LABEL, 		"",
         							            W_PANEL_LENGTH, 	6,
         							            W_PANEL_VALUE, 		"0.0",
         							            W_PANEL_CALLBACK,	0);							               
	W_SET_NUMERIC_VALUE(Ladder_Rotate_Angle_Y, 0.0);							               	
	
	Ladder_Rotate_Angle_Z = W_ADD_PANELITEM(Orientation, W_PANEL_FILL, "Ladder_Rotate_Angle_Z");	
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Rotate_Angle_Z,	W_NUMERIC_FLOAT, 0.0, 180.0, "%.1f");                                                                                                      
	W_REALIZE_PANELITEM(Ladder_Rotate_Angle_Z,	W_PANEL_ROW, 		3, 
												W_PANEL_COL, 		8,
         							            W_PANEL_LABEL, 		"",
         							            W_PANEL_LENGTH, 	6,
         							            W_PANEL_VALUE, 		"0.0",
         							            W_PANEL_CALLBACK, 	0);
	W_SET_NUMERIC_VALUE(Ladder_Rotate_Angle_Z, 0.0);
   
	W_SET_PANELITEM_HANDLER(Ladder_Rotate_Angle_X, "check_rotate_angle");
	W_SET_PANELITEM_HANDLER(Ladder_Rotate_Angle_Y, "check_rotate_angle");   
	W_SET_PANELITEM_HANDLER(Ladder_Rotate_Angle_Z, "check_rotate_angle");
      
	/* 获取图标保存路径 */
	icon_path = Icon_Path;
	/* 图标完整文件名（包含路径） */
	left_rotate_image  = icon_path + "rotateleft16.bmp";
	right_rotate_image = icon_path + "rotateright16.bmp";

	Rotate_By_X_L = W_ADD_PANELITEM(Orientation, W_PANEL_BUTTON, "Rotate_By_X_L");
	W_REALIZE_PANELITEM(Rotate_By_X_L,  W_PANEL_ROW, 			1, 
	                                    W_PANEL_COL, 			4,
							            W_PANEL_LABELIMAGE, 	right_rotate_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT,			W_LAYOUT_HORIZONTAL);   
                                        
	Rotate_By_X_R = W_ADD_PANELITEM(Orientation, W_PANEL_BUTTON, "Rotate_By_X_R");
	W_REALIZE_PANELITEM(Rotate_By_X_R,  W_PANEL_ROW, 			1, 
	                                    W_PANEL_COL, 			16,
							            W_PANEL_LABELIMAGE, 	left_rotate_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT,			W_LAYOUT_HORIZONTAL); 	
                                        
	Rotate_By_Y_L = W_ADD_PANELITEM(Orientation, W_PANEL_BUTTON, "Rotate_By_Y_L");
	W_REALIZE_PANELITEM(Rotate_By_Y_L,	W_PANEL_ROW, 			2, 
	                                    W_PANEL_COL, 			4,
							            W_PANEL_LABELIMAGE, 	right_rotate_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);
                                        
	Rotate_By_Y_R = W_ADD_PANELITEM(Orientation, W_PANEL_BUTTON, "Rotate_By_Y_R");
	W_REALIZE_PANELITEM(Rotate_By_Y_R,  W_PANEL_ROW, 			2, 
	                                    W_PANEL_COL, 			16,
							            W_PANEL_LABELIMAGE, 	left_rotate_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT,			W_LAYOUT_HORIZONTAL);	
                                        
	Rotate_By_Z_L = W_ADD_PANELITEM(Orientation, W_PANEL_BUTTON, "Rotate_By_Z_L");
	W_REALIZE_PANELITEM(Rotate_By_Z_L,	W_PANEL_ROW, 			3, 
	                                    W_PANEL_COL, 			4,
							            W_PANEL_LABELIMAGE, 	right_rotate_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT,			W_LAYOUT_HORIZONTAL); 
                                        
	Rotate_By_Z_R = W_ADD_PANELITEM(Orientation, W_PANEL_BUTTON, "Rotate_By_Z_R");
	W_REALIZE_PANELITEM(Rotate_By_Z_R,  W_PANEL_ROW, 			3, 
	                                    W_PANEL_COL, 			16,
							            W_PANEL_LABELIMAGE, 	left_rotate_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);  
							                   							               			         							         														
	W_SET_PANELITEM_HANDLER(Rotate_By_X_R, "rotate_ladder_handler");
	W_SET_PANELITEM_HANDLER(Rotate_By_X_L, "rotate_ladder_handler");
	W_SET_PANELITEM_HANDLER(Rotate_By_Y_R, "rotate_ladder_handler");
	W_SET_PANELITEM_HANDLER(Rotate_By_Y_L, "rotate_ladder_handler");
	W_SET_PANELITEM_HANDLER(Rotate_By_Z_R, "rotate_ladder_handler");
	W_SET_PANELITEM_HANDLER(Rotate_By_Z_L, "rotate_ladder_handler");
	return(Orientation);
}

check_rotate_angle(item, event_type, dummy)
{
	if (event_type == W_EVENT_ITEM_LEFT){
		st = 0;
		angle = W_GET_NUMERIC_VALUE(item, st);
		if (st == -1){
			W_SET_NUMERIC_VALUE(item, 0.0);
			W_SET_PANELITEM_ARGS(item, W_PANEL_KBDFOCUS, 1);
			return(0);
		}
		return(0);
	}
	return(0);
}

rotate_ladder_handler(item, event_type, button_value)
{
	st = 0;
	x0 = W_GET_NUMERIC_VALUE(Ladder_Position_X,st);
	y0 = W_GET_NUMERIC_VALUE(Ladder_Position_Y,st);
	z0 = W_GET_NUMERIC_VALUE(Ladder_Position_Z,st);

	set = PM_GET_OBJECTS_IN_GROUP(Ladder_Handle);
         
	if (item == Rotate_By_X_L){
		rotate_angle = W_GET_NUMERIC_VALUE(Ladder_Rotate_Angle_X,st);
		angle = 0 - rotate_angle;
		Rotate_Set(x0, y0, z0, "x", set, angle);
	}
	else if (item == Rotate_By_X_R){
		rotate_angle = W_GET_NUMERIC_VALUE(Ladder_Rotate_Angle_X,st);
		angle = rotate_angle;
		Rotate_Set(x0, y0, z0, "x", set, angle);
	}
	else if (item == Rotate_By_Y_L){
		rotate_angle = W_GET_NUMERIC_VALUE(Ladder_Rotate_Angle_Y,st);
		angle = 0 - rotate_angle;
		Rotate_Set(x0, y0, z0, "y", set, angle);
	}
	else if (item == Rotate_By_Y_R){
		rotate_angle = W_GET_NUMERIC_VALUE(Ladder_Rotate_Angle_Y,st);
		angle = rotate_angle;
		Rotate_Set(x0, y0, z0, "y", set, angle);
	}
	else if (item == Rotate_By_Z_L){
		rotate_angle = W_GET_NUMERIC_VALUE(Ladder_Rotate_Angle_Z,st);
		angle = 0-rotate_angle;
		Rotate_Set(x0, y0, z0, "z", set, angle);
	}
	else if (item == Rotate_By_Z_R){
		rotate_angle = W_GET_NUMERIC_VALUE(Ladder_Rotate_Angle_Z,st);
		angle = rotate_angle;
		Rotate_Set(x0, y0, z0, "z", set, angle);
	}     
	return(0);
}

/*
**创建用于移动直梯的面板
*/
create_move_ladder_panel(mainform)
{
	move_ladder = W_ADD_WINDOW(mainform, W_PANEL, "move_ladder");	
	W_REALIZE_WINDOW(move_ladder,	W_FRAME_X,		680,
                                    W_FRAME_Y,		530,
                                    W_FRAME_WIDTH,	100,
                                    W_FRAME_HEIGHT,	200);

	title = W_ADD_PANELITEM(move_ladder, W_PANEL_MESSAGE, "title");
	W_REALIZE_PANELITEM(title,	W_PANEL_ROW,	0,
								W_PANEL_COL,	0,
		                        W_PANEL_LABEL,	"移动直梯");

	seperate_line = W_ADD_PANELITEM(move_ladder, W_PANEL_MESSAGE, "seperate_line");
	W_REALIZE_PANELITEM(seperate_line,	W_PANEL_ROW, 		0,
										W_PANEL_COL, 		7,
		                                W_PANEL_LABEL,		"",
		                                W_PANEL_SEPARATOR, 	1);
		                                 							         
	/* 直梯移动轴 */ 
	Ladder_Move_X = W_ADD_PANELITEM(move_ladder, W_PANEL_FILL, "Ladder_Move_X");	
	W_REALIZE_PANELITEM(Ladder_Move_X,	W_PANEL_ROW, 		1, 
										W_PANEL_COL, 		0,
							            W_PANEL_LABEL, 		"X: ",
							            W_PANEL_LENGTH, 	0,
							            W_PANEL_VALUE, 		"",
							            W_PANEL_CALLBACK,	0);

	Ladder_Move_Y = W_ADD_PANELITEM(move_ladder, W_PANEL_FILL, "Ladder_Move_Y");	
	W_REALIZE_PANELITEM(Ladder_Move_Y,	W_PANEL_ROW, 		2, 
										W_PANEL_COL, 		0,
							            W_PANEL_LABEL, 		"Y: ",
							            W_PANEL_LENGTH, 	0,
							            W_PANEL_VALUE,		"",
							            W_PANEL_CALLBACK,	0);	
										
	Ladder_Move_Z = W_ADD_PANELITEM(move_ladder, W_PANEL_FILL, "Ladder_Move_Z");	
	W_REALIZE_PANELITEM(Ladder_Move_Z,	W_PANEL_ROW, 		3, 
										W_PANEL_COL, 		0,
							            W_PANEL_LABEL, 		"Z: ",
							            W_PANEL_LENGTH, 	0,
							            W_PANEL_VALUE, 		"",
							            W_PANEL_CALLBACK,	0);	

   /* 直梯移动距离 */   
	Ladder_Move_Distance_X = W_ADD_PANELITEM(move_ladder, W_PANEL_FILL, "Ladder_Move_Distance_X");
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Move_Distance_X,	W_NUMERIC_FLOAT,
														0.0, 10000.0,
														"%.0f");	                                                   
	W_REALIZE_PANELITEM(Ladder_Move_Distance_X,	W_PANEL_ROW, 1, 
												W_PANEL_COL, 8,
							                    W_PANEL_LABEL, "",
							                    W_PANEL_LENGTH, 5,
         							            W_PANEL_VALUE, "0.0",
         							            W_PANEL_CALLBACK, 1);        							                
	W_SET_NUMERIC_VALUE(Ladder_Move_Distance_X, 0.0);	

							               
	Ladder_Move_Distance_Y = W_ADD_PANELITEM(move_ladder, W_PANEL_FILL, "Ladder_Move_Distance_Y");	
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Move_Distance_Y,	W_NUMERIC_FLOAT,
                                                        0.0, 10000.0,	
                                                        "%.0f");                                                                                                      
	W_REALIZE_PANELITEM(Ladder_Move_Distance_Y,	W_PANEL_ROW, 		2, 
												W_PANEL_COL, 		8,
         							            W_PANEL_LABEL, 		"",
         							            W_PANEL_LENGTH, 	5,
         							            W_PANEL_VALUE, 		"0.0",
         							            W_PANEL_CALLBACK, 	0);							               
	W_SET_NUMERIC_VALUE(Ladder_Move_Distance_Y, 0.0);							               	
	
	Ladder_Move_Distance_Z = W_ADD_PANELITEM(move_ladder, W_PANEL_FILL, "Ladder_Move_Distance_Z");	
	W_CONFIG_NUMERIC_PANELITEM(Ladder_Move_Distance_Z,	W_NUMERIC_FLOAT,
														0.0, 10000.0,	
														"%.0f");                                                                                                      
	W_REALIZE_PANELITEM(Ladder_Move_Distance_Z,	W_PANEL_ROW, 		3, 
												W_PANEL_COL, 		8,
         							            W_PANEL_LABEL, 		"",
         							            W_PANEL_LENGTH, 	5,
         							            W_PANEL_VALUE, 		"0.0",
         							            W_PANEL_CALLBACK,	0);
	W_SET_NUMERIC_VALUE(Ladder_Move_Distance_Z, 0.0);
   
	W_SET_PANELITEM_HANDLER(Ladder_Move_Distance_X, "check_move_distance");
	W_SET_PANELITEM_HANDLER(Ladder_Move_Distance_Y, "check_move_distance");   
	W_SET_PANELITEM_HANDLER(Ladder_Move_Distance_Z, "check_move_distance");
      
	/* 获取图标保存路径 */
	icon_path = Icon_Path;
	/* 图标完整文件名（包含路径） */
	move_right_image  = icon_path + "move_right.bmp";
	move_left_image = icon_path + "move_left.bmp";

	Move_By_X_N = W_ADD_PANELITEM(move_ladder, W_PANEL_BUTTON, "Move_By_X_N");	
	W_REALIZE_PANELITEM(Move_By_X_N,	W_PANEL_ROW, 			1, 
	                                    W_PANEL_COL, 			3,
							            W_PANEL_LABELIMAGE,		move_left_image, 
							            W_PANEL_BUTTONVALUE,	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);
										
	Move_By_X_P = W_ADD_PANELITEM(move_ladder, W_PANEL_BUTTON, "Move_By_X_P");	
	W_REALIZE_PANELITEM(Move_By_X_P,	W_PANEL_ROW, 			1, 
	                                    W_PANEL_COL, 			15,
							            W_PANEL_LABELIMAGE, 	move_right_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL); 
							                  
	Move_By_Y_N = W_ADD_PANELITEM(move_ladder, W_PANEL_BUTTON, "Move_By_Y_N");	
	W_REALIZE_PANELITEM(Move_By_Y_N,	W_PANEL_ROW, 			2, 
	                                    W_PANEL_COL, 			3,
							            W_PANEL_LABELIMAGE, 	move_left_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);   

	Move_By_Y_P = W_ADD_PANELITEM(move_ladder, W_PANEL_BUTTON, "Move_By_Y_P");	
	W_REALIZE_PANELITEM(Move_By_Y_P,	W_PANEL_ROW, 			2, 
										W_PANEL_COL, 			15,
										W_PANEL_LABELIMAGE, 	move_right_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);							                  
							                  
	Move_By_Z_N = W_ADD_PANELITEM(move_ladder, W_PANEL_BUTTON, "Move_By_Z_N");	
	W_REALIZE_PANELITEM(Move_By_Z_N,	W_PANEL_ROW, 			3, 
	                                    W_PANEL_COL, 			3,
							            W_PANEL_LABELIMAGE, 	move_left_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);   

	Move_By_Z_P = W_ADD_PANELITEM(move_ladder, W_PANEL_BUTTON, "Move_By_Z_P");	
	W_REALIZE_PANELITEM(Move_By_Z_P,    W_PANEL_ROW, 			3, 
	                                    W_PANEL_COL, 			15,
							            W_PANEL_LABELIMAGE, 	move_right_image, 
							            W_PANEL_BUTTONVALUE, 	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);  
							                   							               			         							         														
	W_SET_PANELITEM_HANDLER(Move_By_X_P, "move_ladder_handler");
	W_SET_PANELITEM_HANDLER(Move_By_X_N, "move_ladder_handler");
	W_SET_PANELITEM_HANDLER(Move_By_Y_P, "move_ladder_handler");
	W_SET_PANELITEM_HANDLER(Move_By_Y_N, "move_ladder_handler");
	W_SET_PANELITEM_HANDLER(Move_By_Z_P, "move_ladder_handler");
	W_SET_PANELITEM_HANDLER(Move_By_Z_N, "move_ladder_handler");
	
	return(move_ladder);
}

check_move_distance(item, event_type, dummy)
{
	if (event_type == W_EVENT_ITEM_LEFT){
		st = 0;
		Distance = W_GET_NUMERIC_VALUE(item, st);
		if (st == -1){
			W_SET_NUMERIC_VALUE(item, 0.0);
			dummy = 1;
			W_SET_PANELITEM_ARGS(item, W_PANEL_KBDFOCUS, dummy);
			return(0);
		}
		return(0);
	}
	return(0);
}

move_ladder_handler(item, event_type, button_value)
{
	set = PM_GET_OBJECTS_IN_GROUP(Ladder_Handle);
    
	if (item == Move_By_X_P){
		st = 0;
		distance = W_GET_NUMERIC_VALUE(Ladder_Move_Distance_X,st);
		Move_Set(set, "X", distance);
		x0 = W_GET_NUMERIC_VALUE(Ladder_Position_X,st) + distance;
		W_SET_NUMERIC_VALUE(Ladder_Position_X,x0);
		trans_abs_ref();
	}
	else if (item == Move_By_X_N){
		st = 0;
		distance = 0 - W_GET_NUMERIC_VALUE(Ladder_Move_Distance_X,st);
		Move_Set(set, "X", distance);
		x0 = W_GET_NUMERIC_VALUE(Ladder_Position_X,st) + distance;
		W_SET_NUMERIC_VALUE(Ladder_Position_X,x0);
		trans_abs_ref();      
	}
	else if (item == Move_By_Y_P){
		st = 0;
		distance = W_GET_NUMERIC_VALUE(Ladder_Move_Distance_Y,st);
		Move_Set(set, "Y", distance);
		y0 = W_GET_NUMERIC_VALUE(Ladder_Position_Y,st) + distance;
		W_SET_NUMERIC_VALUE(Ladder_Position_Y,y0);
		trans_abs_ref();      
	}
	else if (item == Move_By_Y_N){
		st = 0;
		distance = 0 - W_GET_NUMERIC_VALUE(Ladder_Move_Distance_Y,st);
		Move_Set(set, "Y", distance);
		y0 = W_GET_NUMERIC_VALUE(Ladder_Position_Y,st) + distance;
		W_SET_NUMERIC_VALUE(Ladder_Position_Y,y0);
		trans_abs_ref();      
	}
	else if (item == Move_By_Z_P){
		st = 0;
		distance = W_GET_NUMERIC_VALUE(Ladder_Move_Distance_Z,st);
		Move_Set(set, "Z", distance);
		z0 = W_GET_NUMERIC_VALUE(Ladder_Position_Z,st) + distance;
		W_SET_NUMERIC_VALUE(Ladder_Position_Z,z0);
		trans_abs_ref();      
	}
	else if (item == Move_By_Z_N){
		st = 0;
		distance = 0 - W_GET_NUMERIC_VALUE(Ladder_Move_Distance_Z,st);
		Move_Set(set, "Z", distance);
		z0 = W_GET_NUMERIC_VALUE(Ladder_Position_Z,st) + distance;
		W_SET_NUMERIC_VALUE(Ladder_Position_Z,z0);
		trans_abs_ref();       
	}  
	return(0);
}

create_command_panel(mainform)
{	
	Command = W_ADD_WINDOW(mainform, W_PANEL, "Command");
	W_REALIZE_WINDOW(Command,	W_FRAME_X, 		0,
							    W_FRAME_Y,		660,
							    W_FRAME_WIDTH,	850,
							    W_FRAME_HEIGHT,	50);
                                
	title = W_ADD_PANELITEM(Command, W_PANEL_MESSAGE, "title");
	W_REALIZE_PANELITEM(title,	W_PANEL_ROW,	0,
		                        W_PANEL_COL,	0,
		                        W_PANEL_LABEL,	"命令");
                                
    seperate_line = W_ADD_PANELITEM(Command, W_PANEL_MESSAGE, "seperate_line");
	W_REALIZE_PANELITEM(seperate_line,	W_PANEL_ROW, 		0,
	                                    W_PANEL_COL, 		3,
		                                W_PANEL_LABEL,		"",
		                                W_PANEL_SEPARATOR,	1);	
		                                 													
	Create_Ladder = W_ADD_PANELITEM(Command, W_PANEL_BUTTON, "Create_Ladder");
	W_REALIZE_PANELITEM(Create_Ladder,	W_PANEL_ROW, 			1, 
										W_PANEL_COL, 			0,
							            W_PANEL_BUTTONIMAGE, 	"创建", 
							            W_PANEL_WIDTH, 			10,
							            W_PANEL_BUTTONVALUE,	501,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(Create_Ladder, "create_ladder_handler");

	Delete_Ladder = W_ADD_PANELITEM(Command, W_PANEL_BUTTON, "Delete_Ladder");
	W_REALIZE_PANELITEM(Delete_Ladder,	W_PANEL_ROW, 			1, 
										W_PANEL_COL, 			11,
							            W_PANEL_BUTTONIMAGE, 	"删除", 
							            W_PANEL_WIDTH, 			10,
							            W_PANEL_BUTTONVALUE, 	503,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(Delete_Ladder, "delete_ladder_handler");

	Browse_Ladder = W_ADD_PANELITEM(Command, W_PANEL_BUTTON, "Browse_Ladder");
	W_REALIZE_PANELITEM(Browse_Ladder,	W_PANEL_ROW, 			1, 
										W_PANEL_COL, 			22,
							            W_PANEL_BUTTONIMAGE, 	"浏览", 
							            W_PANEL_WIDTH, 			10,
							            W_PANEL_BUTTONVALUE, 	504,
							            W_PANEL_CALLBACK, 		1,
							            W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(Browse_Ladder, "browse_ladder_handler");

	Undo = W_ADD_PANELITEM(Command, W_PANEL_BUTTON, "Undo");
	W_REALIZE_PANELITEM(Undo,	W_PANEL_ROW, 			1, 
	                            W_PANEL_COL, 			33,
							    W_PANEL_BUTTONIMAGE, 	"Undo", 
							    W_PANEL_WIDTH, 			10,
							    W_PANEL_BUTTONVALUE, 	505,
							    W_PANEL_CALLBACK, 		1,
							    W_PANEL_LAYOUT, 		W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(Undo, "undo_handler");

	Redo = W_ADD_PANELITEM(Command, W_PANEL_BUTTON, "Redo");
	W_REALIZE_PANELITEM(Redo,	W_PANEL_ROW, 			1, 
	                            W_PANEL_COL, 			44,
							    W_PANEL_BUTTONIMAGE, 	"Redo", 
							    W_PANEL_WIDTH, 			10,
							    W_PANEL_BUTTONVALUE, 	506,
							    W_PANEL_CALLBACK, 		1,
							    W_PANEL_LAYOUT,			W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(Redo, "redo_handler");
				 
	quit = W_ADD_PANELITEM(Command, W_PANEL_BUTTON, "quit");
	W_REALIZE_PANELITEM(quit,	W_PANEL_ROW,         1, 
								W_PANEL_COL,         55,
								W_PANEL_BUTTONIMAGE, "退出", 
							    W_PANEL_WIDTH,       10,
							    W_PANEL_BUTTONVALUE, 507,
							    W_PANEL_CALLBACK,    1,
							    W_PANEL_CLOSEBUTTON, 1,
							    W_PANEL_LAYOUT,      W_LAYOUT_HORIZONTAL);	
	W_SET_PANELITEM_HANDLER(quit, "quit_handler");
	return(Command);
}

/*保留1位小数*/
string_para(float_para)
{
    temp = "";
    S_PRINTF(temp,"%.1f",float_para);
    return temp;
}

/*保存设计参数*/
save_model_size()
{
	para = "";
	if(Ladder_Size_L != 0.0){
		para = para + "L=" + string_para(Ladder_Size_L);
	}
	if(Ladder_Size_W != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//W=" + string_para(Ladder_Size_W);
		}
		else{
			para = para + "W=" + string_para(Ladder_Size_W);
		}
	}	
	if(Ladder_Size_h != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//h=" + string_para(Ladder_Size_h);
		}
		else{
			para = para + "h=" + string_para(Ladder_Size_h);
		}
	}
	if(Ladder_Size_h1 != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//h1=" + string_para(Ladder_Size_h1);
		}
		else{
			para = para + "h1=" + string_para(Ladder_Size_h1);
		}
	}
	if(Ladder_Size_h2 != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//h2=" + string_para(Ladder_Size_h2);
		}
		else{
			para = para + "h2=" + string_para(Ladder_Size_h2);
		}
	}
	if(Ladder_Size_d1 != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//d1=" + string_para(Ladder_Size_d1);
		}
		else{
			para = para + "d1=" + string_para(Ladder_Size_d1);
		}
	}
	if(Ladder_Size_d2 != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//d2=" + string_para(Ladder_Size_d2);
		}
		else{
			para = para + "d2=" + string_para(Ladder_Size_d2);
		}
	}	
	if(Ladder_Size_a != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//a=" + string_para(Ladder_Size_a);
		}
		else{
			para = para + "a=" + string_para(Ladder_Size_a);
		}
	}
	if(Ladder_Size_b != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//b=" + string_para(Ladder_Size_b);
		}
		else{
			para = para + "b=" + string_para(Ladder_Size_b);
		}
	}
	if(Ladder_Size_r != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//r=" + string_para(Ladder_Size_r);
		}
		else{
			para = para + "r=" + string_para(Ladder_Size_r);
		}
	}
	if(Ladder_Size_ad != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//ad=" + string_para(Ladder_Size_ad);
		}
		else{
			para = para + "ad=" + string_para(Ladder_Size_ad);
		}
	}
	if(Ladder_Size_bd != 0.0){
		if(STRLEN(para) > 0){
			para = para + "//bd=" + string_para(Ladder_Size_bd);
		}
		else{
			para = para + "bd=" + string_para(Ladder_Size_bd);
		}
	}
    
	Set_Attribute_Value(Ladder_Handle, LadderSize, para);
}

/*读取设计参数*/
read_model_size()
{
	nth = 0;
	para = PM_GET_OBJDATA(Ladder_Handle,nth,LadderSize);
	if(ISSTRING(para)){	
		/*get seat type & size from parameter of equipment GDL*/
		flag = 1;
		while(flag){
			parameter = STRINGTERM(para,"//");
			if(parameter != ""){
				name = STRINGTERM(parameter,"=");
				value = TAIL(parameter,STRLEN(parameter)-STRLEN(name)-1);
				if(name == "L"){
					Ladder_Size_L = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_L,Ladder_Size_L);
				}
				else if(name == "W"){
					Ladder_Size_W = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_W,Ladder_Size_W);
				}
				else if(name == "h"){
					Ladder_Size_h = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_h,Ladder_Size_h);
				}
				else if(name == "h1"){
					Ladder_Size_h1 = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_h1,Ladder_Size_h1);
				}
				else if(name == "h2"){
					Ladder_Size_h2 = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_h2,Ladder_Size_h2);
				}
				else if(name == "d1"){
					Ladder_Size_d1 = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_d1,Ladder_Size_d1);
				}
				else if(name == "d2"){
					Ladder_Size_d2 = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_d2,Ladder_Size_d2);
				}
				else if(name == "a"){
					Ladder_Size_a = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_a,Ladder_Size_a);
				}
				else if(name == "b"){
					Ladder_Size_b = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_b,Ladder_Size_b);
				}
				else if(name == "r"){
					Ladder_Size_r = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_r,Ladder_Size_r);
				}
				else if(name == "ad"){
					Ladder_Size_ad = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_ad,Ladder_Size_ad);
				}
				else if(name == "bd"){
					Ladder_Size_bd = String_To_Float(value);
					W_SET_NUMERIC_VALUE(Ladder_Para_bd,Ladder_Size_bd);
				}
                
			}
			else{
				flag = 0;            
			}
			para = TAIL(para,STRLEN(para) - STRLEN(parameter) - 2);        
		}
	}
	return(0);
}

browse_ladder_handler(item, event_type, button_value)
{
	W_UNMAP_FRAME(MainWindow);	
	nth_part = 0;
	PM_PICK_OBJECT("浏览模型",nth_part);
	W_MAP_FRAME(MainWindow);   
}

delete_ladder_handler(item, event_type, button_value)
{
	flag = 1;
	while(flag){
		tmp = 0;
		picked_object_handle = PM_PICK_OBJECT("请选择要删除的直梯", tmp, "STRUCTCMP","BEAM");
		if (!ISINT(picked_object_handle)){	   
			/*获取直梯的名称*/
			group_handle = PM_GET_OBJECT_GROUP(picked_object_handle,Group_Type_I);
			if (ISINT(group_handle)){
				U_CONFIRM("此零件不属于任何直梯");	      	
				return(0);
			}	
			group_name = PM_GET_OBJDATA(group_handle,0,MMT_TAG_OBJNAME);
			/* 定义UNDO缓存 */
			st = PM_UM_OPEN_CHANGE("删除直梯" + group_name);	 
      	  
			/* 删除直梯零件 */
			ladder_members = PM_GET_OBJECTS_IN_GROUP(group_handle);
			PM_DELETE_OBJECTS_IN_SET(ladder_members, 0);  
            
			/* 删除直梯 */   
			res = PM_DELETE_OBJECT(group_handle);
         
			/* 直梯删除不成功，撤销相关操作 */
			if (res == -1){
				PM_UM_CLOSE_CHANGE();
				PM_UM_UNDO_LAST_CHANGE();
				return(0);
			}        
			st = PM_UM_CLOSE_CHANGE();  	      	      						
		} 
		else{
			flag = 0;
		} 
	}
   
	/*直梯删除成功，进入创建新直梯状态*/   
	W_SET_PANELITEM_ARGS(Ladder_Name, W_PANEL_VALUE, "Undefined");   
	W_SET_PANELITEM_ARGS(Create_Ladder, W_PANEL_SENSITIVITY,1);   
	Modify_flag = 0;
	return(0);
}

redo_handler(item, event_type, button_value)
{
	res = PM_UM_REDO_LAST_CHANGE();
	if (res == -1){
		U_CONFIRM("已经到了最后一个");
	}
	else{
		ladder_name = PM_GET_OBJDATA(Ladder_Handle,0,MMT_TAG_OBJNAME);
		if(ISSTRING(ladder_name)){ 
			reload_ladder_data(ladder_name);
		}
	}   
	return(0);
}

undo_handler(item, event_type, button_value)
{
	res = PM_UM_UNDO_LAST_CHANGE();
	if (res == -1){
		U_CONFIRM("已经到了最后一个");
	}
	else{
		ladder_name = PM_GET_OBJDATA(Ladder_Handle,0,MMT_TAG_OBJNAME);
		if(ISSTRING(ladder_name)){ 
			reload_ladder_data(ladder_name);
		}
	}
	return(0);
}

delete_ladder_members()
{
	ladder_members = PM_GET_OBJECTS_IN_GROUP(Ladder_Handle);
	PM_DELETE_OBJECTS_IN_SET(ladder_members, 0); 
	return(0);   
}

/*
**加载
*/
load_default_setting()
{
	permision = PM_PREPARE_TO_EDIT_SETTINGS();
	if(permision != 0){
		U_MESSAGE("用户没有保存共享设置的权限");
	}
   
	/*加载直梯信息的默认值*/
	system_name = "";
	st = GET_STRING_DEFAULT("StraightLadder102", "System_Name", system_name);
	if(st == 0){
	    Info_System_Name = system_name;
		Info_System_Id = PM_GET_SYSTEM_ID(system_name);
		W_SET_PANELITEM_ARGS(System_Name, W_PANEL_VALUE, system_name);	   
	}
	else{
		system_name = "Foundation";
		system_id = PM_GET_SYSTEM_ID(system_name);
		if(system_id != -1){
			W_SET_PANELITEM_ARGS(System_Name, W_PANEL_VALUE, system_name);
			Info_System_Name = system_name;
			Info_System_Id = system_id;
		} 	   
	}
	
	/*加载直梯名称*/
	description = "";
	st = GET_STRING_DEFAULT("StraightLadder102", "Info_Ladder_Desc", description);
	if(st == 0){
	    Info_Ladder_Desc = description;
		W_SET_PANELITEM_ARGS(Ladder_Description, W_PANEL_VALUE, description);
	}	
	
	/*加载直梯托盘*/
	planning_unit = "";
	st = GET_STRING_DEFAULT("StraightLadder102", "Planning_Unit", planning_unit);
	if(st == 0){
	    Info_Planning_Unit = planning_unit;
		W_SET_PANELITEM_ARGS(Planning_Unit, W_PANEL_VALUE, planning_unit);
    }
	
	/*加载默认的零件*/
    part_id = "";
    st = GET_STRING_DEFAULT("StraightLadder102","Ladder_Part1", part_id);
	if(st == 0){
		descr = Pid_To_Description(part_id);
        U_MESSAGE("Part1:   " + descr);
		W_SET_PANELITEM_ARGS(Ladder_Part1, W_PANEL_VALUE, descr);
        Ladder_Part1_Pid = part_id;
	}
    
    st = GET_STRING_DEFAULT("StraightLadder102","Ladder_Part2", part_id);
	if(st == 0){
		descr = Pid_To_Description(part_id);
        U_MESSAGE("Part2:   " + descr);
		W_SET_PANELITEM_ARGS(Ladder_Part2, W_PANEL_VALUE, descr);
        Ladder_Part2_Pid = part_id;
	}

    st = GET_STRING_DEFAULT("StraightLadder102","Ladder_Part3", part_id);
	if(st == 0){
		descr = Pid_To_Description(part_id);
        U_MESSAGE("Part3:   " + descr);
		W_SET_PANELITEM_ARGS(Ladder_Part3, W_PANEL_VALUE, descr);
        Ladder_Part3_Pid = part_id;
	} 

    st = GET_STRING_DEFAULT("StraightLadder102","Ladder_Part4", part_id);
	if(st == 0){
		descr = Pid_To_Description(part_id);
        U_MESSAGE("Part4:   " + descr);
		W_SET_PANELITEM_ARGS(Ladder_Part4, W_PANEL_VALUE, descr);
        Ladder_Part4_Pid = part_id;
	} 

    st = GET_STRING_DEFAULT("StraightLadder102","Ladder_Part5", part_id);
	if(st == 0){
		descr = Pid_To_Description(part_id);
        U_MESSAGE("Part5:   " + descr);
		W_SET_PANELITEM_ARGS(Ladder_Part5, W_PANEL_VALUE, descr);
        Ladder_Part5_Pid = part_id;
	} 

    st = GET_STRING_DEFAULT("StraightLadder102","Ladder_Part6", part_id);
	if(st == 0){
		descr = Pid_To_Description(part_id);
        U_MESSAGE("Part6:   " + descr);
		W_SET_PANELITEM_ARGS(Ladder_Part6, W_PANEL_VALUE, descr);
        Ladder_Part6_Pid = part_id;
	} 
    
	/*load default value of ladder size*/
	size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_L", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_L, size);
		Ladder_Size_L = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_L, 1500.00);
		Ladder_Size_L = 1500.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_L", Ladder_Size_L); 
	}
	
    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_W", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_W, size);
		Ladder_Size_W = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_W, 400.00);
		Ladder_Size_W = 400.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_W", Ladder_Size_W); 
	}
	
	size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_h, size);
		Ladder_Size_h = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_h, 300.00);
		Ladder_Size_h = 300.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h", Ladder_Size_h); 
	}

	size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h1", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_h1, size);
		Ladder_Size_h1 = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_h1, 150.00);
		Ladder_Size_h1 = 150.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h1", Ladder_Size_h1); 
	}

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h2", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_h2, size);
		Ladder_Size_h2 = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_h2, 150.00);
		Ladder_Size_h2 = 150.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_h2", Ladder_Size_h2); 
	}	

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d1", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_d1, size);
		Ladder_Size_d1 = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_d1, 300.00);
		Ladder_Size_d1 = 300.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d1", Ladder_Size_d1); 
	}	

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d2", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_d2, size);
		Ladder_Size_d2 = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_d2, 300.00);
		Ladder_Size_d2 = 300.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_d2", Ladder_Size_d2); 
	}	

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_a", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_a, size);
		Ladder_Size_a = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_a, 50.00);
		Ladder_Size_a = 50.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_a", Ladder_Size_a); 
	}	

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_b", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_b, size);
		Ladder_Size_b = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_b, 100.00);
		Ladder_Size_b = 100.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_b", Ladder_Size_b); 
	}	

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_r", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_r, size);
		Ladder_Size_r = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_r, 15.00);
		Ladder_Size_r = 15.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_r", Ladder_Size_r); 
	}	

    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_ad", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_ad, size);
		Ladder_Size_ad = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_ad, 90.00);
		Ladder_Size_ad = 90.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_ad", Ladder_Size_ad); 
	}	
    
    size = 0.0;
	st = GET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_bd", size);
	if(st == 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_bd, size);
		Ladder_Size_bd = size;
	}	
	else if (st != 0){
		W_SET_NUMERIC_VALUE(Ladder_Para_bd, 90.00);
		Ladder_Size_bd = 90.00;	  
		SET_FLOAT_DEFAULT("StraightLadder102", "Ladder_Para_bd", Ladder_Size_bd); 
	}	
    
	return(0);
}

initialize()
{
    /* 获取当前光标点坐标并显示到面板中 */
    /* get the current position and display value of coordinate */
    x0 = 0;y0 = 0;z0 = 0;   
    PM_GET_CURRENT_LOC(x0, y0, z0);   
    W_SET_NUMERIC_VALUE(Ladder_Position_X, x0);
    W_SET_NUMERIC_VALUE(Ladder_Position_Y, y0);
    W_SET_NUMERIC_VALUE(Ladder_Position_Z, z0);
   
    /* 将绝对坐标转换成相对坐标并显示到面板中 */
    /* convert abstract coordinate value into reference and display on panel */
    x_ref = "";   y_ref = "";   z_ref = "";
    x_offset = 0; y_offset = 0; z_offset = 0;

    Ladder_X0 = x0;
    Ladder_Y0 = y0;
    Ladder_Z0 = z0;
   
    res = GetReferenceCoords( x0, y0, z0, x_ref, x_offset, y_ref, y_offset, z_ref, z_offset);
    if (res == 0){   
        W_SET_PANELITEM_ARGS(Ladder_Position_Xref, W_PANEL_VALUE, x_ref);
        W_SET_PANELITEM_ARGS(Ladder_Position_Yref, W_PANEL_VALUE, y_ref);
        W_SET_PANELITEM_ARGS(Ladder_Position_Zref, W_PANEL_VALUE, z_ref);

        W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, x_offset);
        W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, y_offset);
        W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, z_offset);      
    }
    else if (res == -1){     
        W_SET_PANELITEM_ARGS(Ladder_Position_Xref, W_PANEL_VALUE, "Unset");
        W_SET_PANELITEM_ARGS(Ladder_Position_Yref, W_PANEL_VALUE, "Unset");
        W_SET_PANELITEM_ARGS(Ladder_Position_Zref, W_PANEL_VALUE, "Unset");

        W_SET_NUMERIC_VALUE(Ladder_Position_Xoff, 0);
        W_SET_NUMERIC_VALUE(Ladder_Position_Yoff, 0);
        W_SET_NUMERIC_VALUE(Ladder_Position_Zoff, 0); 
        U_CONFIRM("参考坐标系定义不正确");           
    }
    
    Modify_flag = 0;
    Part11 = A_ALLOC(15);
    Part12 = A_ALLOC(15);
    Part13 = A_ALLOC(15);
    Part14 = A_ALLOC(15);
    Part15 = A_ALLOC(15);
    Part16 = A_ALLOC(15);
    
    Part21 = A_ALLOC(15);
    Part22 = A_ALLOC(15);
    
    Part31 = A_ALLOC(15);
    Part32 = A_ALLOC(15);
    Part33 = A_ALLOC(15);
    Part34 = A_ALLOC(15);
    
    Part41 = A_ALLOC(15);
    Part42 = A_ALLOC(15);
    Part43 = A_ALLOC(15);
    Part44 = A_ALLOC(15);
    
    Part51 = A_ALLOC(15);
    Part52 = A_ALLOC(15);
    Part53 = A_ALLOC(15);
    Part54 = A_ALLOC(15);
    
    Part61 = A_ALLOC(15);
    Part62 = A_ALLOC(15);
    Part63 = A_ALLOC(15);
    Part64 = A_ALLOC(15);
    
    load_default_setting();
    return(0);
}

main()
{
	mainform  = create_top_frame();	
	Panel_1 = create_template_panel(mainform);
	Panel_2 = create_info_panel(mainform);
	Panel_3 = create_material_panel(mainform);
	Panel_4 = create_command_panel(mainform);
	Panel_5 = create_parameter_panel(mainform);
	Panel_6 = create_position_panel(mainform);
	Panel_7 = create_rotate_ladder_panel(mainform);
	Panel_8 = create_move_ladder_panel(mainform);
	initialize();	
	MainWindow = mainform;
	W_MAP_FRAME(mainform);
	W_RUN_FRAME(mainform);
	W_UNMAP_FRAME(mainform);
	W_DESTROY_FRAME(mainform);
}
